### ISSUE TITLE
UX (user experience) and usability improvements (please create separate issues instead of appending)

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1060]
Please share your ideas on how to make the life of others easier.

- [x] #1105
- [ ] Make Add Stop in routing discoverable by users #5674 
- [ ] Render the name of the track on the map #8706
- [ ] Render bookmark names on the map but in a smart way, to avoid cluttering #3164
- [ ] Clearly differentiate underground subway stations from their entrances on the map and in the search results #1778 
- [ ] Clarify what is "default sorting" for bookmarks #5680
- [ ] Increase the size of the number (of the exit to take) in the roundabout in navigation mode or redesign roundabouts #4018
- [ ] Fit more useful info on search screen (see https://github.com/organicmaps/organicmaps/issues/1060#issuecomment-912953428) #5675
- [ ] Redesign Save button for bookmarks on Android. It is not obvious, and users lose already typed data by accidentally pressing Back instead of Save. #5680
- [ ] Download elevations/hill-shading separately from the maps data for faster map updates.
- [ ] Better handling of the default set for newly added bookmarks, see [this comment](https://github.com/organicmaps/organicmaps/issues/1060#issuecomment-939266080) #5680
- [ ] While building a route, allow to select roads with a single tap for faster alternate routes. Done

**Comment by Raphael0** [comment]
I'll start with a few:

- Being able to drag and drop the starting point, stops and end point of a route with a long tap to quickly adapt the route
- Being able to rearrange the order of bookmark lists
- Confirmation dialog when deleting a bookmark list (not needed for single bookmarks, but on iOS a simple swipe to the left will delete a list containing hundreds of bookmarks with no confirmation dialog)

Thank you for all the amazing work!

**Comment by pluja** [comment]
- Ability to change the color of an imported KML route path (Orange color is confusing with some roads).

**Comment by bkqtnte10** [comment]
- Increase the size of the number (of the exit to take) in the roundabout in navigation mode.

**Comment by j-james** [comment]
- [ ] Make the "Map Layers" button more useful - add bus / tram routes or other public transportation overlays as options 
  - (many cities, in America in particular, don't have an "underground" or subway)
- [ ] Fetch limited maps on-demand while downloading or not downloaded
- [ ] Make navigation a quicker process
  - After clicking the route button, you still have to select "route from" and "route to" for the start and end place.
- [ ] Being able to select arbitrary locations to route to (ex. the middle of a road)

**Comment by biodranik** [comment]
Regarding "After clicking the route button, you still have to select "route from" and "route to" for the start and end place.": do you have any ideas how to make it better?

**Comment by j-james** [comment]
I think that Organic Maps could assume that the user is looking for a destination after pressing the route button, and act as if the user had tapped and then pressed the "route to" button. So the user flow would go: tap route button ==> Organic Maps pops up the "Add a destination" prompt ==> tap destination ==> Organic Maps pops up the "Add a starting point" (or use location) prompt ==> tap starting point or location icon ==> route.

**Comment by biodranik** [comment]
I am not sure that it's the best user experience. Probably that button should be removed.

**Comment by Raphael0** [comment]
Just for perspective, in 4 years of Maps.me/OrganicMaps I have never used the generic "route to" button. I always plan a route after choosing a place on the map

**Comment by jgg2O** [comment]
I don't understand why you can't just input this into the map EX: "3217 W Yuma St, Phoenix, AZ 85009, United States" to navigate to but it always wants to route to EX: "Yuma St, Phoenix, AZ" 
This goes for home address to like I don't want to be routed to the street I want to get routed to the exact address

Device Info:
iPhone 11
iOS: 14.7
App Version: 2021.08.09.1

**Comment by biodranik** [comment]
Thanks, @jgg2O, but it's not UX, it's a bug in our search which doesn't recognize W as West. We'll fix that, I mentioned it in #1120

**Comment by biodranik** [comment]
Reduce height of controls to fit more useful information on the screen:

![image](https://user-images.githubusercontent.com/170263/132092075-4c5d5149-645c-4d77-ba6a-401da53c5a1c.png)

**Comment by bnitkin** [comment]
Would it be possible to render elevation isolines in feet or meters, depending on the `Measurement units` selection? It's a little odd to see elevations in meters while distances are miles.

Even re-labelling the same lines in feet would be nice (i.e. 1700m = 5580').

Thanks! I just downloaded the app yesterday. Having an offline map with topolines and navigation is great.

**Comment by biodranik** [comment]
@bnitkin See #1067

**Comment by zyphlar** [comment]
Regarding the navigation flow, I agree that I am not used to deciding on a route before I found the destination, which means that I often search for a POI, and then wish that the option to route to that destination or even route to a location that I've long pressed on, existed. Instead I have to back out, click the route button, search for the same thing I just searched for, and then specify that my starting point is gps, which is a very unexpected way of doing things. Sometimes the option to route to a search result exists, but not always, which adds to the confusion.

**Comment by biodranik** [comment]
@zyphlar do you have an Android 11 device? There is bug #1065 now when the bottom panel disappears after the search. It should be fixed soon.

**Comment by zyphlar** [comment]
Yes ok that would help greatly, I didn't think to expect a panel to be there

**Comment by vbertola** [comment]
Some simple but useful bookmark features, from a heavy Maps.me user that just switched (thanks for the effort!) and has about 50 bookmark lists with 5-300 POIs each:

- Add/customize bookmark colors: on Android, in the color selection dialog, there are two empty slots that could provide two additional colors; there are two grey shades that are almost impossible to tell apart, so one is wasted; it would be good if I could simply customize a color (at system level, for all bookmarks at once), e.g. by keeping pressed over a color and entering a custom color hex code;

- Mass copy/move/delete POIs: from within the list of POIs of a single bookmark list, select any number of POIs (e.g. keeping pressed over a POI selects it and changes to selection mode, then pressing over more POIs adds them to the selection) and copy or move them to a new list or to an existing one, or delete them at once (possibly after a confirmation dialog).

- Mass backup: have an option somewhere to create a tar/zip/whatever of all bookmark lists (optionally, selecting only some of them) that can then be shared externally.

More generally speaking, it would be good to switch to an open, standard format for bookmark files - even better if it were a text format so that files could even be edited by hand.

**Comment by pluja** [comment]
Being able to select to what bookmark list I want to save a certain bookmark. It defaults to the last list I added something.

**Comment by biodranik** [comment]
> Being able to select to what bookmark list I want to save a certain bookmark. It defaults to the last list I added something.

How would you implement that? How it will look like for users? Any examples or ideas?

**Comment by biodranik** [comment]
When a user hides the last used set of bookmarks, the same set is displayed again when adding a new bookmark. Because a new bookmark is added into the last used set. And if it was hidden, it becomes visible (to show a newly added bookmark).

A better UX would be to choose another set instead, which is visible on the map (probably the one which was either the last used one or was the last unhidden one by the user). If all sets are hidden, then probably a new set should be created.

**Comment by Donkey-Doug** [comment]
> Regarding "After clicking the route button, you still have to select "route from" and "route to" for the start and end place.": do you have any ideas on how to make it better?

I think google maps nailed it. Just have a search button. After a place has been found/selected, show options on what to do next. Currently there are too many options shown to the user. Keep it simple. I suggest only a search button. Three tabs after pressing search are visible: history, places and bookmarks.

**Comment by biodranik** [comment]
> I think google maps nailed it. Just have a search button. After a place has been found/selected, show options on what to do next. Currently there are too many options shown to the user. Keep it simple. I suggest only a search button. Three tabs after pressing search are visible: history, places and bookmarks.

Bookmarks is a very popular feature of OM. It should be accessible in one click.

**Comment by Donkey-Doug** [comment]
> The only problem is that a long tap is not discoverable by users.
> 
> P.S. bookmarks search of course should be implemented. Is there already an issue for that?

We do not need long press. See #1409 for a good implementation.

**Comment by pluja** [comment]
@biodranik I think that long press is a well established action amongst most users. Spotify, YouTube, and most apps use some kind of long-press actions. It's the first thing that I tried when I wanted to add to another list that was not the last used. But I understand that you do not want to introduce it to the app design (although there is already a long press for selecting a location on the map that is not a POI).

Another option is to always ask where you want to add the bookmark (showing the list as the photo on my last comment). I think that this is how Google Maps does it, they always ask which list you want to add a new bookmark. This would also be a great option as LRU (Last Recent Used) is not a great option; as a user I do not add so much bookmarks (at most one or two every 2 or 3 days) this means that, with that timespan between bookmarks, I will be adding different kinds of bookmarks. The actual process for moving a bookmark is tedious, and I think it would be much better to be always asked where to add a bookmark instead of defaulting it to the last used.

**Comment by biodranik** [comment]
Long tap solution is friendlier than always showing the list. It is just not discoverable by users. Even long tap on the map area is not discoverable by many people. I'm telling you from actual support statistics, not out of my mind.

**Comment by arnaudvergnet** [comment]
I think the map update UX needs some improvements. You currently have to go to the map download section manually, which a lot of users will not do. You have a little red badge on the bottom bar to notify an update is available, but this is not enough.

I would love to be notified when an update for the area I am looking for is available. A simple and non-intrusive way would be to show an icon next to the layers button for example. The icon would be hidden if no update is available, and appear if one is for the currently visible area (center of the screen).

Here is an example of the icon showing an update is available for the current zone:

![Screenshot_20211222-223417_Organic_Maps](https://user-images.githubusercontent.com/80701113/147158018-fce67b1a-d65d-495b-875e-a27c5e2611bd.png)

Also, a good way to make updating and downloading maps globally more user friendly would be let the user show a layer above the map (with the help of a button easily reachable), with areas in different colors depending on their update status.
Areas would depend on the zoom level (country on low zoom, then regions, ...). If a zone is fully downloaded, display it in green, if it is partially (some sub-regions are up to date, some not), display it in orange, and if a zone is not downloaded or no sub-regions are up to date, show in red.

| Zoomed out in France | Zoomed in on the orange region |
| - | - |
|  ![france](https://user-images.githubusercontent.com/80701113/147159243-6f56266a-4f6f-44c1-8494-73373ad5c278.png) | ![midi-pyrenees](https://user-images.githubusercontent.com/80701113/147159020-3d2d7b1c-f85a-4f1b-9cad-c469c4893e1a.png) |

**Comment by pastk** [comment]
> 
> Also, a good way to make updating and downloading maps globally more user friendly would be let the user show a layer above the map (with the help of a button easily reachable), with areas in different colors depending on their update status. Areas would depend on the zoom level (country on low zoom, then regions, ...). If a zone is fully downloaded, display it in green, if it is partially (some sub-regions are up to date, some not), display it in orange, and if a zone is not downloaded or no sub-regions are up to date, show in red.

There is https://github.com/organicmaps/organicmaps/issues/1356 for this part already. Please add your comments there.

**Comment by arnaudvergnet** [comment]
> There is #1356 for this part already. Please add your comments there.

Damn I missed it, thanks!

**Comment by DOFfactory** [comment]
My suggestions: 

- please provide a functionality of turning the LCD off, and whenever there is an instruction to turn, change course, etc. to turn the LCD on (best for cycling navigation)
- is there a way to maybe share the downloaded maps with OsmAnd's maps? This would help to save some space on the device...

**Comment by smartyw** [comment]
Allow the user to select the colour of the pointer which indicates present position and direction. The dark blue is very hard to see sometimes when outdoors on a bright day with a phone inside a waterproof case with water droplets on it (example of the extreme conditions navigation takes place in sometimes!). In addition, some of us have less than perfect eyesight so this is as much an "accessibility" requirement rather than just "usability". I believe that for me, a bright red pointer would be easier to see but making it user selectable would be the way to go.

Additionally, the design of the pointer (on Android anyway) is such that it has three vertices. When it's hard to see your screen because of the conditions, sometimes you can make out only one of the vertices and it is easy to mistake it for the "front" vertex indicating direction. If the pointer had only one pointed vertex there would never be any confusion over which direction the pointer was pointing in. So maybe the back could be rounded, a semi-circle for example and the front, pointed as it is now. Not sure if the pointer is created by Organic Maps code or is provided by Android though.

And finally, for the same accessibility reasons, being able to set the size of the pointer would be very useful.

**Comment by biodranik** [comment]
@smartyw Can you please recommend new/better colors and shapes? Ideally, draw an example screenshot.

**Comment by smartyw** [comment]
**Pointer Usability Challenges**

- When the application is used outdoors, say for hiking or cycling, bright light or wet weather can make the screen harder to read in general. 
- Sometimes it is necessary to carry a smartphone in a protective, waterproof case with a transparent screen and this can make viewing detail in the application harder still with reflections on the cover of the case and perhaps water droplets adding to the issue. 
- Some people have impaired vision and there are many distinct types of issue. For example, colour blindness or difficulty distinguishing shapes when contrast is low.
- The design of the current pointer with its multiple vertices, coupled with personal or environmental viewing challenges can lead to ambiguity or mistakes in identifying the direction indicated.

**Analysis**

![organic_maps_pointer](https://user-images.githubusercontent.com/1387793/162432761-68a5e48c-fe01-4ad8-acd7-2e260ad4cb01.png)

The pointer has three main vertices, labelled A, B and C in the above screen shot. These have an internal angle formed by the two edges incident upon them of less than 90 degrees. The fourth vertex has an internal angle of greater than 90 degrees.

The similarity of the angles at A, B and C is the source of the ambiguity of the icon when some part of it is obscured by reflection, poor contrast or a physical obstacle such as a water droplet. If all you can make out is vertex C, for example, then it may be perceived as the main directional indicator at vertex A.

**Proposal**
It is proposed that users be afforded the option to choose from a number of pointer designs, sizes and colours. A selection of options will be provided with the intention of offering something which is optimal for a wide variety of users in a variety of conditions.

- Users should be able to select the pointer size along a sliding scale from small to very large. The current cursor size should be considered to be “medium” sized.
- Users to be able to select any custom RGB colour from a colour palette. 
- Pointer design to be simplified and based on solid shading only.
- Pointer design should reduce or eliminate the ambiguity in the current design regarding direction indication which is caused by three of the four vertices having edges incident upon them at a similar and acute angle. One possible design is shown below.

![Organic Maps Pointers](https://user-images.githubusercontent.com/1387793/162433230-d9617dbe-4b6b-4bcd-afab-6e55d98fb067.png)

![Organic Maps Pointer on Map Example](https://user-images.githubusercontent.com/1387793/162433254-518f173a-0f5c-4d2c-a73d-5b6a0407fd1a.png)

The design shown here has only a single point which therefore cannot be confused with other vertices.
The current design should continue to be an option for those users that are happy with it.

That's it from me. Just my $0.02.

**Comment by biodranik** [comment]
Thanks for the details! The idea to make the pointer better recognizable is a good one, and we probably won't support different pointers to save development time and reduce UX complexity.
Another important improvement is to make the GPS error radius (a blue circle around the arrow) more recognizable. Now it's hard to understand if the position is a precise one or not if the circle radius is large (approximate location by WiFi or cellular towers).

**Comment by smartyw** [comment]
Excellent, thanks. Yes, the accuracy indication could be very useful as well as long as it doesn't add too much visual complexity around the pointer icon itself. Keeping it simple is the key to eliminating ambiguity. Looking forward to seeing where you decide to take this! :-)

**Comment by DOFfactory** [comment]
I second @smartyw's comment, make it please optional, on a bike ride one does not necessarily need a radius visible, but the arrow is more important. I wonder whether the pointers proposed above should have a little bit of transparency, sometimes it is important to see what is 'under' the pointer, especially in 3D close view

**Comment by smartyw** [comment]
Maybe only show the accuracy radius after the user taps the pointer. Show it for (say) 3 seconds and then remove it. Yes, I agree with @DOFfactory that direction is most important. Adding more information associated with the pointer may make it harder to use sometimes.

Not sure about transparency. Sometimes it will be useful, other times it will reduce clarity. You can usually discover information under the pointer by changing the zoom level.

**Comment by zyphlar** [comment]
My only thought with the fully round back is that if the arrow points downwards it can look very much like poi pins in other GPS apps. Maybe rounded corners without being a full circle or having the confusing angular highlights would accomplish the same goal.

Here's a bad sketch of the approximate shape I have in mind:

![](https://i.imgur.com/x4fFRpq_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by vbertola** [comment]
While we are here, I will point out that I find it extremely annoying when I open the app and it automatically moves my position back to my current position. Often I am working on the map to plan a trip which will happen in the future, maybe on the other side of the world. I would like to continue working in that area for some time without being brought back home every time I have to reopen the app. There is a very visible UI button to do that if you need, why should it also happen automatically?

**Comment by biodranik** [comment]
@vbertola you're probably speaking about #934

**Comment by Nic787** [comment]
CarPlay search should allow to quickly search gaz/recharge station, parking or other stuffs like the mobile app. Having to type what you want to find is very difficult when driving.

**Comment by tvld** [comment]
I just installed an hour ago. By biggest question is real-time traffic information layer. But i can't find any information on the home page nor in the app itself. What am i missing?))

**Comment by zyphlar** [comment]
@tvld where did you get the idea that Organic Maps had realtime traffic info?

**Comment by j-james** [comment]
I don't know of any comprehensive sources for realtime traffic info. [There's are a couple relevant](https://github.com/osmandapp/Osmand/issues/1432) [OSMAnd issues about it](https://github.com/osmandapp/OsmAnd/issues/6878).

**Comment by tvld** [comment]
@zyphlar nowhere. It's just my desire to get rid of everything Alphabet / Google (who also own Waze). And for me, the "deal-breaker" is real-time traffic info. Hence "the wish is the father of the thought",  as we say it :-)

**Comment by pm4rcin** [comment]
There's an [app in f-droid](https://f-droid.org/en/packages/org.traffxml.roadeagle/) but it has only roadworks and similiar. However support for traffic data is planned but the problem is that many data sources have different format so developer has to work hard to convert them. But it'd be great if support for it was implemented.

**Comment by not-available-username** [comment]
> **Pointer Usability Challenges**
> 
>     * When the application is used outdoors, say for hiking or cycling, bright light or wet weather can make the screen harder to read in general.
> 
>     * Sometimes it is necessary to carry a smartphone in a protective, waterproof case with a transparent screen and this can make viewing detail in the application harder still with reflections on the cover of the case and perhaps water droplets adding to the issue.
> 
>     * Some people have impaired vision and there are many distinct types of issue. For example, colour blindness or difficulty distinguishing shapes when contrast is low.
> 
>     * The design of the current pointer with its multiple vertices, coupled with personal or environmental viewing challenges can lead to ambiguity or mistakes in identifying the direction indicated.
> 
> 
> **Analysis**
> 
> 
> The pointer has three main vertices, labelled A, B and C in the above screen shot. These have an internal angle formed by the two edges incident upon them of less than 90 degrees. The fourth vertex has an internal angle of greater than 90 degrees.
> 
> The similarity of the angles at A, B and C is the source of the ambiguity of the icon when some part of it is obscured by reflection, poor contrast or a physical obstacle such as a water droplet. If all you can make out is vertex C, for example, then it may be perceived as the main directional indicator at vertex A.
> 
> **Proposal** It is proposed that users be afforded the option to choose from a number of pointer designs, sizes and colours. A selection of options will be provided with the intention of offering something which is optimal for a wide variety of users in a variety of conditions.
> 
>     * Users should be able to select the pointer size along a sliding scale from small to very large. The current cursor size should be considered to be “medium” sized.
> 
>     * Users to be able to select any custom RGB colour from a colour palette.
> 
>     * Pointer design to be simplified and based on solid shading only.
> 
>     * Pointer design should reduce or eliminate the ambiguity in the current design regarding direction indication which is caused by three of the four vertices having edges incident upon them at a similar and acute angle. One possible design is shown below.
> 
> 
> 
> The design shown here has only a single point which therefore cannot be confused with other vertices. The current design should continue to be an option for those users that are happy with it.
> 
> That's it from me. Just my $0.02.

Hey! I agree that the current pointer is not always readable and in my opinion is also a bit _outdated_ in terms of design, but I agree with @biodranik to not spend time on the support of different pointers and colours.

I think that with some minor changes the readability could be improved by a lot, essentially with a brighter colour (same hue, increased saturation and value) and with a flat design.

I used #0075ff for the pointer and for the GPS error radius and I made the corner round (I will round them better with the other PC, with a newer version of Illustrator). I also made a version with outlines on pointer and error radius and in my opinion this improves a lot the readability (the circle has an opacity of 10% and the outline 20%).

Please let me know if this could work and I'll share the vector file!


![a](https://user-images.githubusercontent.com/92886370/176001360-24ef0bac-4d49-4fd1-89d8-25832c0dedc3.jpg)
![b](https://user-images.githubusercontent.com/92886370/176001369-ffb46d1e-43ff-4a42-a7c1-69e371aa0ef2.jpg)
![c](https://user-images.githubusercontent.com/92886370/176001370-97df0848-6e51-4b75-86e4-49359a72a2f4.jpg)
![d](https://user-images.githubusercontent.com/92886370/176001375-ef7f74c8-58a4-46b6-93b6-d688301a06f0.jpg)

**Comment by biodranik** [comment]
1. What about the night theme?
2. The bigger issue is when users test OM at home and do not see the error radius circle (because it's too large and takes the whole screen), and complain that OM shows them the wrong location. That results in negative reviews and support complaints. Any ideas on how to better/easier handle it?

**Comment by not-available-username** [comment]
> 1. What about the night theme?
> 
>     2. The bigger issue is when users test OM at home and do not see the error radius circle (because it's too large and takes the whole screen), and complain that OM shows them the wrong location. Well, even when they see the circle, they don't always understand its meaning. That results in negative reviews and support complaints. Any ideas on how to better/easier handle it?

1. I think that should work as well, I'll made some test tomorrow
2. I never had this issue, in the mountains, it happens that the GPS takes a bit to locate me, but I never see a large circle (maybe because the iPhone is very fast refine precision). Maybe you can set the app to zoom out to show the border of the circle? After the user can zoom in again, but is forced to see the whole circle. I guess that with my proposal the user sees the whole screen with a blue shade and can guess that there is something bigger, at least IMHO this is an expected behaviour, similar to other apps.

**Comment by TheAdventurer64** [comment]
> > 1. What about the night theme?
> 
> > 
> 
> >     2. The bigger issue is when users test OM at home and do not see the error radius circle (because it's too large and takes the whole screen), and complain that OM shows them the wrong location. Well, even when they see the circle, they don't always understand its meaning. That results in negative reviews and support complaints. Any ideas on how to better/easier handle it?
> 
> 
> 
> 1. I think that should work as well, I'll made some test tomorrow
> 
> 2. I never had this issue, in the mountains, it happens that the GPS takes a bit to locate me, but I never see a large circle (maybe because the iPhone is very fast refine precision). Maybe you can set the app to zoom out to show the border of the circle? After the user can zoom in again, but is forced to see the whole circle. I guess that with my proposal the user sees the whole screen with a blue shade and can guess that there is something bigger, at least IMHO this is an expected behaviour, similar to other apps.
> 
> 

Any progress?

**Comment by biodranik** [comment]
In mountains, there is no wifi/cellular location with low accuracy. Only the precise GPS.

Zooming out because of the accuracy is an unexpected behavior (imagine you're zoomed to your house, and then it suddenly jumps out).

**Comment by the4anoni** [comment]
Organic maps don't like overlay for camera on Galaxy S10
![Screenshot_20221002-202255_Organic Maps](https://user-images.githubusercontent.com/13403084/193469828-d848eb10-c043-4692-8d7f-51554077dd1a.png)

**Comment by arnaudvergnet** [comment]
> Organic maps don't like overlay for camera on Galaxy S10

This will be fixed soon! See https://github.com/organicmaps/organicmaps/pull/3495

**Comment by rikrd** [comment]
- return Bookmarks in search results
- return Contacts with addresses in search results
- add easy access to special points such as Home and Work when looking for routes
- when showing a navigation result for a Bike, show with different style when following or not a bike lane

**Comment by nyanmeister** [comment]
Not sure if this fits, but I'd like more of the tags to show up in info-cards (the details when you click a PoI):
- Accessibility for dogs (https://wiki.openstreetmap.org/wiki/Key:dog)
- Access conditions of toilets for businesses (https://wiki.openstreetmap.org/wiki/Key:toilets)
- Fee for accessing a feature (https://wiki.openstreetmap.org/wiki/Key:fee, and fee:amount in particular.)
- Description tag, useful for clarifying details that are hard or impossible to tag precisely and have render.

This comes from a focus on tourist access where I map.

**Comment by Josh-SMU** [comment]
Add Android UI to all builds so you can change which UI to use (important for mobile Linux)

**Comment by biodranik** [comment]
> Add Android UI to all builds so you can change which UI to use (important for mobile Linux)

What does it mean? To implement the same UI as it is now on Android, but for Linux?

**Comment by Josh-SMU** [comment]
Yes that is exactly correct

**Comment by d4f5409d** [comment]
> > **Pointer Usability Challenges**
> > 
> >     * When the application is used outdoors, say for hiking or cycling, bright light or wet weather can make the screen harder to read in general.
> > 
> >     * Sometimes it is necessary to carry a smartphone in a protective, waterproof case with a transparent screen and this can make viewing detail in the application harder still with reflections on the cover of the case and perhaps water droplets adding to the issue.
> > 
> >     * Some people have impaired vision and there are many distinct types of issue. For example, colour blindness or difficulty distinguishing shapes when contrast is low.
> > 
> >     * The design of the current pointer with its multiple vertices, coupled with personal or environmental viewing challenges can lead to ambiguity or mistakes in identifying the direction indicated.
> > 
> > 
> > **Analysis**
> > 
> > 
> > The pointer has three main vertices, labelled A, B and C in the above screen shot. These have an internal angle formed by the two edges incident upon them of less than 90 degrees. The fourth vertex has an internal angle of greater than 90 degrees.
> > 
> > The similarity of the angles at A, B and C is the source of the ambiguity of the icon when some part of it is obscured by reflection, poor contrast or a physical obstacle such as a water droplet. If all you can make out is vertex C, for example, then it may be perceived as the main directional indicator at vertex A.
> > 
> > **Proposal** It is proposed that users be afforded the option to choose from a number of pointer designs, sizes and colours. A selection of options will be provided with the intention of offering something which is optimal for a wide variety of users in a variety of conditions.
> > 
> >     * Users should be able to select the pointer size along a sliding scale from small to very large. The current cursor size should be considered to be “medium” sized.
> > 
> >     * Users to be able to select any custom RGB colour from a colour palette.
> > 
> >     * Pointer design to be simplified and based on solid shading only.
> > 
> >     * Pointer design should reduce or eliminate the ambiguity in the current design regarding direction indication which is caused by three of the four vertices having edges incident upon them at a similar and acute angle. One possible design is shown below.
> > 
> > 
> > 
> > The design shown here has only a single point which therefore cannot be confused with other vertices. The current design should continue to be an option for those users that are happy with it.
> > 
> > That's it from me. Just my $0.02.
> 
> Hey! I agree that the current pointer is not always readable and, in my opinion, is also a bit _outdated_ in terms of design, but I agree with @biodranik to not spend time on the support of different pointers and colours.
> 
> I think that with some minor changes the readability could be improved by a lot, essentially with a brighter colour and flat design.
> 
> I used #1f95f0 for the pointer and for the GPS error radius and I made the corner round (the circle has an opacity of 10% and the outline 20%).
> 
> Please let me know if this could work and I'll share the vector file!
> 
> _[edit: changed colour, refined design of the point and deleted versions without outline]_
> 
> ![Tavola disegno 4](https://user-images.githubusercontent.com/92886370/176041462-ce40fc89-7acb-4862-b4a2-d0d880172be3.jpg)
> 
> 
> ![2](https://user-images.githubusercontent.com/92886370/176154066-381a0d43-1115-4e92-b875-ba9deebcb4ff.jpg)
> 
>  

I really love this! This looks like it was always like this! This fits to the app's theme so well, I can't even describe! Wonderful work! Simple, but neat, just like the app's concept! With this, we could easily switch even accent colors and have a green arrow, while we can still differentiate it from the background! 
+15 points from me for this one

**Comment by not-available-username** [comment]
> 
> I really love this! This looks like it was always like this! This fits to the app's theme so well, I can't even describe! Wonderful work! Simple, but neat, just like the app's concept! With this, we could easily switch even accent colors and have a green arrow, while we can still differentiate it from the background! +15 points from me for this one

Thank you so much! I really hope it will be implemented soon, but it seems that it’s stuck at the proposal stage… #2853

**Comment by smartyw** [comment]
The pointer design proposed by @d4f5409d 
 looks pretty good. I'd suggest adding it as an optional beta feature that can be activated by the user. Then some proper field testing can take place. I like what I see here though, no question.

**Comment by not-available-username** [comment]
> The pointer design proposed by @d4f5409d looks pretty good. I'd suggest adding it as an optional beta feature that can be activated by the user. Then some proper field testing can take place. I like what I see here though, no question.

@d4f5409d quoted a message with my proposal ;) I hope it will be adopted or tested soon, but it's been a while since the suggestion was made 😅

**Comment by biodranik** [comment]
Nobody is blocking you to help us and implement a pull request with a new pointer, so everyone can see and test it on a device.

**Comment by adrium** [comment]
First of all, awesome app, thanks! :heart:

I think #1373 would be great to have.

**Comment by phu9Suop** [comment]
Search preferences : Prefer identical spelling over distance. 
I feel stupid , when I key in a Place - off the visual map - and the app offers me everything but not the identical named item.
I tap Laxenb , the text completion offers Laxenburg , I confirm and the app gives me Luxemburg. 
Laxenburg is not to be seen in anywhere the results. In this case both targets are several 100 kms away.

**Comment by jwmh** [comment]
https://github.com/organicmaps/organicmaps/issues/5398

**Comment by dandud100** [comment]
Regarding Tracks: Display the start and end point of an gpx track.

Maybe make the track clickable on the or display the name of it somewhere else.

**Comment by bveldkamp** [comment]
>> Being able to select to what bookmark list I want to save a certain bookmark. It defaults to the last list I added something.

> How would you implement that? How it will look like for users? Any examples or ideas?

Maybe like how YouTube does this. It saves bookmarks to the last used list, but then shows a pop-up for a few seconds, "Bookmark saved to [name], click to change". Tapping the pop-up will give the option to move the Bookmark to a different list.

**Comment by dpriskorn** [comment]
"Render the name of the track on the map" 
what's meant by track? Highway=track?

**Comment by RedAuburn** [comment]
> "Render the name of the track on the map" what's meant by track? Highway=track?

it means imported GPX/KML tracks :)

**Comment by stibinator** [comment]
When you search for a location the results are displayed without enough detail. For example if I search for High St, there are half a dozen results, but they don't display what suburb each one is in. Same for searches for say, stores or venues, when there are multiple results you have to open each one to find which it is.

**Comment by stibinator** [comment]
![Uploading Screenshot_20231008_121459_Organic Maps.jpg…]()

**Comment by stibinator** [comment]
In a related issue, there's no way back to the results once you have clicked on one of them, going back takes you back to the main map screen, so you have to repeat the search.

**Comment by pastk** [comment]
I think its good to create separate issues for ideas voiced here, because ideas just got lost in this super long thread..

**Comment by dpriskorn** [comment]
@biodranik are you currently using GitHub peoject? 
If not, I highly recommend it.
It has nice kanban functionality so you can easily overview the issues
Also you can group by tags, priority, milestone, etc.

**Comment by biodranik** [comment]
GitHub Projects require linking to existing issues anyway for convenient functionality. If we focus on sorting around existing 1800+ issues, you won't get Organic Maps updates in the next two or free months :) Any ideas and help on organizing them here are greatly appreciated.

**Comment by dpriskorn** [comment]
I have been in the same situation with fewer issues so I understand what you mean.
What about using milestones as a start?

**Comment by biodranik** [comment]
Agree. Any volunteers to carefully help with that?

**Comment by nelsonaelam** [comment]
With all the awesome new data in the December 23rd update for the outdoors view (thank you!!!), I think a key/legend would be very helpful. When I pull up similar data in OpenStreetMap there seems to be a key.

**Comment by biodranik** [comment]
Try to tap or long-tap on unknown objects.

**Comment by nelsonaelam** [comment]
Thanks! That works sometimes in areas with other infrastructure, but in a forest area with a lot of different types of trails/tunnels/etc, I just get Forest/Grassland/Shelter and nothing for the trails there. An example of this is at 59.447472, 17.903183.

If the long press option worked as described, I still think a key with a list of the different trail/road types and the colors associated would be helpful. On openstreetmap, there is an "i" icon on the right hand side of the screen that has this information in the form of a map key.

**Comment by pastk** [comment]
> Thanks! That works sometimes in areas with other infrastructure, but in a forest area with a lot of different types of trails/tunnels/etc, I just get Forest/Grassland/Shelter and nothing for the trails there. An example of this is at 59.447472, 17.903183.

This specific example is a contour line / altitude isoline and its deliberately not selectable and its assumed that people who have enabled contour lines know what it is.

Other lines (e.g. different trail types, rivers, fences, etc.) and area fills are long-tappable / selectable.

**Comment by d1820** [comment]
The ability on an import to select the icon color. When you import different  files they all get assigned the same one. Then you have to go one by one to change them. With 1000s of waypoints  no way im gonna do that. The color is super important  especially  when looking at multiple lists on the map. Gaia GPS lets you assign at the folder level or select all in a folder and change for all. This goes well with the multi edit suggestion above.

**Comment by biodranik** [comment]
@d1820 there is already #5637

**Comment by rtsisyk** [comment]
@oleg-rswll, it would be greatly appreciated if you could create separate tickets for all the mentioned issues, tagging them with https://github.com/organicmaps/organicmaps/labels/UX, and then close this ticket.

**Comment by oleg-rswll** [comment]
Went through all the requests in this issue, at the top and the comments - all of them are already in existing issues.

For the future, this is a very bad approach to cram all these requests and have conversations about all of them mixed together into one issue.  It is extremely time consuming and offers no benefit or value to do it this way, from the perspective of the requestor, for product team, or development.

Closing this Issue.

**Comment by Miro-UX-debug** [comment]
There are a lot of requests, but I find it difficult to give feedback because suggestions date 4 years back. Besides I am unaware of all planned actions in the product roadmap. However, one of the things, which I noticed through the heurist analysis and competitor research is that Organic Maps has an opportunity to improve routing options with the ability to add stops and adjust road conditions (e.g., avoid tolls). I've noticed the team is working on solutions.
 
Make Add Stop in routing discoverable by users [Make route planning simpler and intuitive #5674](https://github.com/organicmaps/organicmaps/issues/5674)
