### ISSUE TITLE
Meta-Issue: More Rich POI Information

### ISSUE THREAD

**Issue by Unkn0wnCat** [organicmaps/organicmaps#1892]
*Ref: #1888, #1879,  #1233, #1052*

## Purpose of this issue

This issue is to be used to discuss implementation of this feature and track completion.

For discussions on if and where logos should be shown for brands, please see #1052.

## To-Do
- [ ] Display description field on POIs (#1888)
- [ ] Add description field to POI editor (#1233)
- [ ] Source description data from Wikidata (#1052) 
- [ ] Show logos in search for banks, gas stations, mobile_phone shops, energy_supplier shops, post_office or courier shops ([Part of #1052](https://github.com/organicmaps/organicmaps/discussions/1052#discussioncomment-1253618))
- - [ ] Source logo data from Wikidata for specified categories

*This list was made from existing issues, as well as the solutions discussed in #1052, please discuss those points there*

*Please comment with `@Unkn0wnCat` if I forgot anything!*

## For Discussion
*Participate in the discussion in #1052*

- Display Logos in POI-Detail-View
- Display Logos in search for additional POI-Types
- Additional data from WikiData that may be of use

### Declined
- Display Logos on Map, as this would clutter the map and give an advantage to big brands

**Comment by Unkn0wnCat** [comment]
Request for comment: @AlertSubject, @Raphael0, @starwatcher11, @vachan-maker, @biodranik, @dbf256, @gtrus21, @biodranik

Please let me know if you feel this is a good compromise. I've done my best to reflect all your input in this issue. 🙂

**Comment by j13m126** [comment]
@Unkn0wnCat   please add these issues: #1302, #1303, #1301. thanks!

**Comment by biodranik** [comment]
Good, formally, displaying descriptions can be split into 3 tasks:
1. Generator support (maps contain descriptions).
2. Add descriptions displaying in Android UI
3. Add descriptions displaying in iOS UI

Editing is also split into two tasks: editing it on Android, and editing it on iOS.

**Comment by vachan-maker** [comment]
Thank you for your work. This is good.

**Comment by endim8** [comment]
another: https://github.com/organicmaps/organicmaps/issues/2431
