### ISSUE TITLE
Missing or wrong icons list

### ISSUE THREAD

**Issue by not-available-username** [organicmaps/organicmaps#1919]
This is a list of wrong icons and missing ones:
(there is [a guide](https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md#how-to-add-a-new-icon) how to add/update icons)

Wrong icons:
- [x] `aerialway=station` now displayed as a train or something similar #2715
- [x] `information=guidepost` now displayed as 🛈
`information=trail_blaze` now displayed as 🛈
`information=board` now displayed as 🛈
`amenity=vending_machine` not displayed
`information=map` now displayed as 🛈
- [ ] it'll be great to have better icons for `amenity=waste_disposal` and `landuse=landfill` (they use a small waste bucket icon now) https://github.com/organicmaps/organicmaps/issues/6240
- [x] #2319
- [x] #2187
- [x] #2748
- [x] a current convenience shop icon is not very good, maybe use [this](https://materialdesignicons.com/icon/store-outline)
- [x] #2121
- [x] `shop-chemist` #6393

New icons wanted:
- [ ] #1917 icons needed for a lot of new POIs
- [x] #563 `amenity=events_venue`
- [x] some generic icon for a gate - we have an icon for a `lift_gate`, but other types are displayed as small dots and its not easy to spot them looking at the map.
Also for other features that block the way potentially: `bollard`, `block`, `barrier` etc. At the moment they're just dots, but should be more visible. Maybe some generic small cross icon will do. Arguably it shouldn't be a big red cross, because usually a barrier means a way is not passable for cars, but pedestrians and bicycles are fine.
- [ ] #11458
- [x] #3271 
- [x] #3287

**Comment by pastk** [comment]
More features in need of icons: #1916 and #1917

**Comment by pastk** [comment]
Also it'll be great to have better icons for `amenity=waste_disposal` and `landuse=landfill` #1839

**Comment by pastk** [comment]
Some generic icon for a gate - we have an icon for a `lift_gate`, but other types are displayed as small dots and its not easy to spot them looking at the map.

**Comment by pastk** [comment]
We need an icon for `amenity=shelter`, atm a picnic table icon is used which is not good
![Screenshot_1643651968](https://user-images.githubusercontent.com/18434508/151854216-7725d4dd-eb84-4d8b-a08d-b05d9ca8a54f.png)

**Comment by pastk** [comment]
`amenity=events_venue` #563

**Comment by pastk** [comment]
To add an icon:
1. add an svg icon to `data/styles/clear/style-clear/symbols/` (and to style-night)
preferably use icons from sources listed in data/copyright.html
2. add icon rendering/visibility rules into `data/styles/clear/include/Icons.mapcss` and to "navigation style" `data/styles/vehicle/include/Icons.mapcss`
3. run `tools/unix/generate_symbols.sh` to add new icons into the skin files
4. run `tools/unix/generate_drules.sh` to generate drawing rules for the new icons

**Comment by pastk** [comment]
> There is no specific "bookmark" icon for playgrounds at the moment. For some reason it falls back to using `bookmark-entertainment-m.png` - need to check the code to understand why.

It needs to be changed in `map/bookmark_helpers.cpp`

**Comment by Explorer256** [comment]
The driving school icon is missing. Points of this type are displayed as labels shifted down.

**Comment by j5k** [comment]
`vending=excrement_bags` has wrong icon

**Comment by pastk** [comment]
Anyone who feels like finishing the cave entrance icon? :)
https://github.com/organicmaps/organicmaps/issues/949#issuecomment-1484089448

**Comment by pastk** [comment]
`shop-chemist`

> A shop selling articles of personal hygiene, cosmetics, and household cleaning products.

but it has a very misleading icon atm

![icon](https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/chemist-m.svg)

Carto's icon is OK, but could be better

**Comment by dvdmrtnz** [comment]
Closing this meta-issue. All missing icons listed here have their own issue. They can be found by searching by [Icons](https://github.com/organicmaps/organicmaps/issues?q=sort%3Aupdated-desc%20label%3AIcons) label. Any new request should be added on their own issue.
