### ISSUE TITLE
iOS: publish the app on AppStore

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#31]
- [ ] Choose app category
- [ ] Screenshots
- [ ] Description, keywords proofreading
- [ ] App icon?
- [ ] Welcome article?
- [ ] Fix known bugs :)
