### ISSUE TITLE
Android Auto Checklist

### ISSUE THREAD

**Issue by AndrewShkrob** [organicmaps/organicmaps#4096]
Screens:
- [x] Main (https://github.com/organicmaps/organicmaps/pull/3806)
   <details>
   <summary>Example</summary>
   <img width="912" src="https://user-images.githubusercontent.com/10351358/204114336-51c33232-3f8f-4590-b1cf-1a7655bdaa6c.png">
   </details>

- [x] Settings (https://github.com/organicmaps/organicmaps/pull/3806)
   <details>
      <summary>Example</summary>
      <details>
         <summary>Main</summary>
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204114398-7969279c-ea0e-4353-b483-0eb8ef24e38f.png">
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204114404-4afeda73-4e7b-4efe-a1ab-e9c3133d3c0a.png">
      </details>
      <details>
         <summary>Driving Options</summary>
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204114519-038200b4-279b-4517-9478-ca1d00992c5e.png">
      </details>
      <details>
         <summary>Help</summary>
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204114563-2c60ba68-aeab-496d-92ec-9e99d3506c8e.png">
      </details>
   </details>

- [ ] Bookmarks (https://github.com/organicmaps/organicmaps/pull/3806)
   <details>
      <summary>Example</summary>
      <details>
         <summary>Bookmark Categories</summary>
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204364693-cb8ea9a5-0d57-4c7b-ba72-1b413e81ae2f.png">
      </details>
      <details>
         <summary>Bookmark</summary>
         <img width="912" src="https://user-images.githubusercontent.com/10351358/204364730-b2598229-61b0-4a36-bc29-ba11f01103b4.png">
      </details>
   </details>
> <b>Note</b>
> Current implementation contains UI only. `Item.onClick` needs to be implemented.

- [ ] Categories (https://github.com/organicmaps/organicmaps/pull/3806)
   <details>
      <summary>Example</summary>
      <img width="912" src="https://user-images.githubusercontent.com/10351358/204114600-9be945c0-55d9-4ba8-a4d0-724beed0885c.png">
   </details>
> <b>Note</b>
> Current implementation contains UI only. `Item.onClick` needs to be implemented.

- [ ] Search (https://github.com/organicmaps/organicmaps/pull/3806)
   <details>
      <summary>Example</summary>
      <img width="912" src="https://user-images.githubusercontent.com/10351358/204114583-1f8fb79c-85be-43f9-8dfd-a2c562111d9a.png">
   </details>
> <b>Note</b>
> Current implementation contains UI only. Search logic and `Item.onClick` need to be implemented.

- [ ] Route Planning
   <details>
      <summary>Example from Google Maps</summary>
      <img width="912" alt="Screenshot 2022-12-16 at 21 26 02" src="https://user-images.githubusercontent.com/10351358/208183453-93a078a0-ded6-4c6b-91ac-3abd7f1825e2.png">
   </details>
   <details>
      <summary>Example from Yandex Maps</summary>
      <img width="912" alt="Screenshot 2022-12-16 at 21 26 02" src="https://user-images.githubusercontent.com/10351358/208184243-19390340-b713-47ce-991f-262c2a52d969.png">
   </details>

- [ ] Navigation
   <details>
      <summary>Example from Google Maps</summary>
      <img width="912" alt="Screenshot 2022-12-16 at 21 26 02" src="https://user-images.githubusercontent.com/10351358/208185002-64f4a740-6fd6-422c-8e70-f6295ef84a25.png">
   </details>
   <details>
      <summary>Example from Yandex Maps</summary>
      <img width="912" alt="Screenshot 2022-12-16 at 21 26 02" src="https://user-images.githubusercontent.com/10351358/208184701-ac06b901-e373-4945-b5ea-316ce9a7316d.png">
   </details>

To implement:
- [ ] CarApi
   The current implementation of map screens uses `MapTemplate` which requires `CarApi 5`.
   What to do:
* Check (dynamically or during the app initialization) the Car API level
* Decide what template to use during the screen creation:
   * `NavigationTemplate` (for CarApi < 5) vs `MapTemplate` (for CarApi >= 5)
   * `List/GridTemplate` (for CarApi < 5) vs `MapTemplate` (for CarApi >= 5)
   * And the same for other screens

- [ ] Buttons
   Design buttons for screens.

- [ ] Location
   Implement `Location` button that will support different location types.
   Implement location detection

- [ ] `SurfaceRenderer`
   Properly implement surface callbacks like `Move`, `Click`, `Scale` and so on.

- [ ] Separate `SharedPreferences` for AA
   It will be good to store settings for AA in a separate `SharedPreferences`.
   Use case:
   Scaled fonts for AA and standard fonts for the phone.

- [ ] AA connection detection (Until the many surfaces rendering support)
   Add the possibility of switching between AA and phone.

- [ ] Build route on the phone and navigate on AA

Features:
- [ ] Hardware sensors support
   AA supports fetching data from car sensors.
   What can be used:
* Speed
* Compass
* Location
* Energy/Fuel level to build an optimal route
* Toll card to automatically detect whether to use toll roads or not
* Fuel/Charger type for a better search of gas station

- [ ] Rendering on many surfaces
   Support rendering on AA and phone simultaneously

**Comment by rtsisyk** [comment]
This is a good plan, thanks for organizing things! My wish is to prioritize "Build route on the phone and navigate on AA" over "Route Planning".

**Comment by michaelblyons** [comment]
If you have success in getting AA to work when Play Store is not the managing installer (e.g. F-Droid, Aurora, etc.), many people would be interested.

**Comment by biodranik** [comment]
Is it possible in theory? Has anyone already done it?

**Comment by michaelblyons** [comment]
I do not know of a _navigation_ app that has done so successfully. That is why it would be exciting. 😁 

Other classes of apps (media and messaging) have worked after activating AA's developer tools (tap the "Version" row many times) and enabling apps from unknown sources.

I have a [short summary](https://github.com/osmandapp/OsmAnd/issues/15400#issuecomment-1437432187) of what has worked for people for OsmAnd~. Most of what I know is collated from GitHub discussions for OsmAnd, NewPipe, AntennaPod, and from GitLab for F-Droid data.

**Comment by rtsisyk** [comment]
2023-08-19 QA findings:

#5757 #5758 #5759 #5760 #5761 #5762 #5763 #5764 #5765 #5766 #5767 #5768

**Comment by rtsisyk** [comment]
> Split-screen layout

Seems to be working.

> Download maps screen
> Message Screen for notifications

My suggestion is to redirect to phone for permissions & map downloading.

>  Day/Night Mode

Seems to be working.

> Deep links support

What doesn't work? Probably move to the next phase.

>  Hardware sensors support

Location from the phone works fine. Probably move to the next phase. 

> Rendering on many surfaces

This is a complex task that require significant refactoring. Probably move to the next phase. 

> Separate SharedPreferences for AA

What is impact of that?

> In build.gradle: Fix for app/organicmaps/util/FileUploadWorker.java:14: error: cannot access ListenableFuture

What is significance of this?

**Comment by rtsisyk** [comment]
I see the following short-term list of issues to fix:

- [ ] https://github.com/organicmaps/organicmaps/issues/5757
- [ ] https://github.com/organicmaps/organicmaps/issues/5758
- [ ] https://github.com/organicmaps/organicmaps/issues/5766
- [ ] https://github.com/organicmaps/organicmaps/pull/4611
- [ ] The app must provide a “test drive” mode that simulates driving. 
- [ ] https://github.com/organicmaps/organicmaps/issues/5763
- [ ] https://github.com/organicmaps/organicmaps/issues/5765 (probably not a bug, but need to check)
- [ ] https://github.com/organicmaps/organicmaps/issues/5767
- [ ] https://github.com/organicmaps/organicmaps/issues/5759

**Comment by kaibagley** [comment]
> If you have success in getting AA to work when Play Store is not the managing installer (e.g. F-Droid, Aurora, etc.), many people would be interested.

Has there been any word on this front?

**Comment by 0xunusedusername** [comment]
> > If you have success in getting AA to work when Play Store is not the managing installer (e.g. F-Droid, Aurora, etc.), many people would be interested.
> 
> Has there been any word on this front?

Tried enabling allow unknown sources in the AA settings and that didn't work either 😞

**Comment by Thestroyer** [comment]
> If you have success in getting AA to work when Play Store is not the managing installer (e.g. F-Droid, Aurora, etc.), many people would be interested.

Im curious why, after installing OM via [install with options](https://github.com/zacharee/InstallWithOptions) it is still not displayed in AA apps (with unknown sources enabled). In setting it is clearly written it comes from Play Store.
