### ISSUE TITLE
Android: replace copyrighted icons and images

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#52]
From [NOTICE](NOTICE):

> All images and media content are Copyright (C) 2020 My.com B.V. (Mail.Ru Group)

The full list of copyrighted icons:
- [ ] ./android/res/drawable-*/abc_ic_ab_back_mtrl_am_alpha.png
- [ ] ./android/res/drawable-*/all_pass_premium_60.png
- [ ] ./android/res/drawable-*/all_pass_premium_61.png
- [ ] ./android/res/drawable-*/all_pass_premium_62.png
- [ ] ./android/res/drawable-*/all_pass_premium_63.png
- [ ] ./android/res/drawable-*/bg_circle_night.png
- [ ] ./android/res/drawable-*/bg_circle.png
- [ ] ./android/res/drawable-*/bg_circle_pressed_night.png
- [ ] ./android/res/drawable-*/bg_circle_pressed.png
- [ ] ./android/res/drawable-*/bg_place_page_head_closed.9.png
- [ ] ./android/res/drawable-*/bg_place_page_head_closed_night.9.png
- [ ] ./android/res/drawable-*/bg_place_page_head_open.9.png
- [ ] ./android/res/drawable-*/bg_place_page_head_open_night.9.png
- [ ] ./android/res/drawable-*/bookmark_disabled.png
- [ ] ./android/res/drawable-*/card_frame.9.png
- [ ] ./android/res/drawable-*/card_frame_night.9.png
- [ ] ./android/res/drawable-*/ic_12px_rating_star_off.png
- [ ] ./android/res/drawable-*/ic_12px_rating_star_on.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_generic.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_lightrail.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_metro.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_monorail.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_train.png
- [ ] ./android/res/drawable-*/ic_20px_route_planning_walk.png
- [ ] ./android/res/drawable-*/ic_24px_clear.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner18.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner19.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner1.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner20.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner2.png
- [ ] ./android/res/drawable-*/ic_24px_logo_partner3.png
- [ ] ./android/res/drawable-*/ic_24px_rating_bad.png
- [ ] ./android/res/drawable-*/ic_24px_rating_coming_soon.png
- [ ] ./android/res/drawable-*/ic_24px_rating_excellent.png
- [ ] ./android/res/drawable-*/ic_24px_rating_good.png
- [ ] ./android/res/drawable-*/ic_24px_rating_horrible.png
- [ ] ./android/res/drawable-*/ic_24px_rating_normal.png
- [ ] ./android/res/drawable-*/ic_24px_rating_star_off.png
- [ ] ./android/res/drawable-*/ic_24px_rating_star_on.png
- [ ] ./android/res/drawable-*/ic_24px_route_planning_walk.png
- [ ] ./android/res/drawable-*/ic_24px_route_point_a.png
- [ ] ./android/res/drawable-*/ic_24px_route_point_b.png
- [ ] ./android/res/drawable-*/ic_24px_route_point_c.png
- [ ] ./android/res/drawable-*/ic_24_px_settings.png
- [ ] ./android/res/drawable-*/ic_ab_left.png
- [ ] ./android/res/drawable-*/ic_ab_right.png
- [ ] ./android/res/drawable-*/ic_ad_dark.png
- [ ] ./android/res/drawable-*/ic_add_members.png
- [ ] ./android/res/drawable-*/ic_address.png
- [ ] ./android/res/drawable-*/ic_ad_light.png
- [ ] ./android/res/drawable-*/ic_ads_fb.png
- [ ] ./android/res/drawable-*/ic_altitude_difference.png
- [ ] ./android/res/drawable-*/ic_arrow_down.png
- [ ] ./android/res/drawable-*/ic_avoid_ferry.png
- [ ] ./android/res/drawable-*/ic_avoid_tolls.png
- [ ] ./android/res/drawable-*/ic_avoid_unpaved.png
- [ ] ./android/res/drawable-*/ic_bank.png
- [ ] ./android/res/drawable-*/ic_bike.png
- [ ] ./android/res/drawable-*/ic_blog.png
- [ ] ./android/res/drawable-*/ic_booking.png
- [ ] ./android/res/drawable-*/ic_bookmark_animals.png
- [ ] ./android/res/drawable-*/ic_bookmark_bar.png
- [ ] ./android/res/drawable-*/ic_bookmark_buddhism.png
- [ ] ./android/res/drawable-*/ic_bookmark_building.png
- [ ] ./android/res/drawable-*/ic_bookmark_christianity.png
- [ ] ./android/res/drawable-*/ic_bookmark_entertainment.png
- [ ] ./android/res/drawable-*/ic_bookmark_finish.png
- [ ] ./android/res/drawable-*/ic_bookmark_food.png
- [ ] ./android/res/drawable-*/ic_bookmark_gas.png
- [ ] ./android/res/drawable-*/ic_bookmark_hotel.png
- [ ] ./android/res/drawable-*/ic_bookmark_islam.png
- [ ] ./android/res/drawable-*/ic_bookmark_judaism.png
- [ ] ./android/res/drawable-*/ic_bookmark_medicine.png
- [ ] ./android/res/drawable-*/ic_bookmark_money.png
- [ ] ./android/res/drawable-*/ic_bookmark_mountain.png
- [ ] ./android/res/drawable-*/ic_bookmark_museum.png
- [ ] ./android/res/drawable-*/ic_bookmark_none.png
- [ ] ./android/res/drawable-*/ic_bookmark_parking.png
- [ ] ./android/res/drawable-*/ic_bookmark_park.png
- [ ] ./android/res/drawable-*/ic_bookmark_shop.png
- [ ] ./android/res/drawable-*/ic_bookmark_sights.png
- [ ] ./android/res/drawable-*/ic_bookmarks_off.png
- [ ] ./android/res/drawable-*/ic_bookmarks_on.png
- [ ] ./android/res/drawable-*/ic_bookmark_sport.png
- [ ] ./android/res/drawable-*/ic_bookmark_start.png
- [ ] ./android/res/drawable-*/ic_bookmark_swim.png
- [ ] ./android/res/drawable-*/ic_bookmark_transport.png
- [ ] ./android/res/drawable-*/ic_bookmark_viewpoint.png
- [ ] ./android/res/drawable-*/ic_bookmark_water.png
- [ ] ./android/res/drawable-*/ic_brand_megafon_green.png
- [ ] ./android/res/drawable-*/ic_cancel.png
- [ ] ./android/res/drawable-*/ic_car.png
- [ ] ./android/res/drawable-*/ic_category_atm_night.png
- [ ] ./android/res/drawable-*/ic_category_atm.png
- [ ] ./android/res/drawable-*/ic_category_bank_night.png
- [ ] ./android/res/drawable-*/ic_category_bank.png
- [ ] ./android/res/drawable-*/ic_category_children_night.png
- [ ] ./android/res/drawable-*/ic_category_children.png
- [ ] ./android/res/drawable-*/ic_category_eat_night.png
- [ ] ./android/res/drawable-*/ic_category_eat.png
- [ ] ./android/res/drawable-*/ic_category_entertainment_night.png
- [ ] ./android/res/drawable-*/ic_category_entertainment.png
- [ ] ./android/res/drawable-*/ic_category_food_night.png
- [ ] ./android/res/drawable-*/ic_category_food.png
- [ ] ./android/res/drawable-*/ic_category_fuel_night.png
- [ ] ./android/res/drawable-*/ic_category_fuel.png
- [ ] ./android/res/drawable-*/ic_category_hospital_night.png
- [ ] ./android/res/drawable-*/ic_category_hospital.png
- [ ] ./android/res/drawable-*/ic_category_hotel_night.png
- [ ] ./android/res/drawable-*/ic_category_hotel.png
- [ ] ./android/res/drawable-*/ic_category_luggagehero_night.png
- [ ] ./android/res/drawable-*/ic_category_luggagehero.png
- [ ] ./android/res/drawable-*/ic_category_megafon_night.png
- [ ] ./android/res/drawable-*/ic_category_megafon.png
- [ ] ./android/res/drawable-*/ic_category_nightlife_night.png
- [ ] ./android/res/drawable-*/ic_category_nightlife.png
- [ ] ./android/res/drawable-*/ic_category_parking_night.png
- [ ] ./android/res/drawable-*/ic_category_parking.png
- [ ] ./android/res/drawable-*/ic_category_pharmacy_night.png
- [ ] ./android/res/drawable-*/ic_category_pharmacy.png
- [ ] ./android/res/drawable-*/ic_category_police_night.png
- [ ] ./android/res/drawable-*/ic_category_police.png
- [ ] ./android/res/drawable-*/ic_category_post_night.png
- [ ] ./android/res/drawable-*/ic_category_post.png
- [ ] ./android/res/drawable-*/ic_category_shopping_night.png
- [ ] ./android/res/drawable-*/ic_category_shopping.png
- [ ] ./android/res/drawable-*/ic_category_toilet_night.png
- [ ] ./android/res/drawable-*/ic_category_toilet.png
- [ ] ./android/res/drawable-*/ic_category_tourism_night.png
- [ ] ./android/res/drawable-*/ic_category_tourism.png
- [ ] ./android/res/drawable-*/ic_category_transport_night.png
- [ ] ./android/res/drawable-*/ic_category_transport.png
- [ ] ./android/res/drawable-*/ic_category_wifi_night.png
- [ ] ./android/res/drawable-*/ic_category_wifi.png
- [ ] ./android/res/drawable-*/ic_chart_pin.png
- [ ] ./android/res/drawable-*/ic_checkbox_add.png
- [ ] ./android/res/drawable-*/ic_checkmark.png
- [ ] ./android/res/drawable-*/ic_chevron_right_white.png
- [ ] ./android/res/drawable-*/ic_clear.png
- [ ] ./android/res/drawable-*/ic_clear_rounded_night.png
- [ ] ./android/res/drawable-*/ic_clear_rounded.png
- [ ] ./android/res/drawable-*/ic_close.png
- [ ] ./android/res/drawable-*/ic_close_spinner.png
- [ ] ./android/res/drawable-*/ic_coordinates.png
- [ ] ./android/res/drawable-*/ic_crown.png
- [ ] ./android/res/drawable-*/ic_cuisine.png
- [ ] ./android/res/drawable-*/ic_deal_dark.png
- [ ] ./android/res/drawable-*/ic_deal_light.png
- [ ] ./android/res/drawable-*/ic_delete.png
- [ ] ./android/res/drawable-*/ic_direction_fullscreen.png
- [ ] ./android/res/drawable--*/ic_direction_fullscreen.png
- [ ] ./android/res/drawable-*/ic_direction_pagepreview.png
- [ ] ./android/res/drawable-*/ic_disclosure_down.png
- [ ] ./android/res/drawable-*/ic_disclosure_up.png
- [ ] ./android/res/drawable-*/ic_discovery_error.png
- [ ] ./android/res/drawable-*/ic_dog_bg_night.png
- [ ] ./android/res/drawable-*/ic_dog_bg.png
- [ ] ./android/res/drawable-*/ic_dog.png
- [ ] ./android/res/drawable-*/ic_done.png
- [ ] ./android/res/drawable-*/ic_downloader_done_night.png
- [ ] ./android/res/drawable-*/ic_downloader_done.png
- [ ] ./android/res/drawable-*/ic_downloader_download_night.png
- [ ] ./android/res/drawable-*/ic_downloader_download.png
- [ ] ./android/res/drawable-*/ic_downloader_folder_done_night.png
- [ ] ./android/res/drawable-*/ic_downloader_folder_done.png
- [ ] ./android/res/drawable-*/ic_downloader_folder_night.png
- [ ] ./android/res/drawable-*/ic_downloader_folder.png
- [ ] ./android/res/drawable-*/ic_downloader_retry.png
- [ ] ./android/res/drawable-*/ic_downloader_update.png
- [ ] ./android/res/drawable-*/ic_download.png
- [ ] ./android/res/drawable-*/ic_down.png
- [ ] ./android/res/drawable-*/ic_drop_down.png
- [ ] ./android/res/drawable-*/ic_edit.png
- [ ] ./android/res/drawable-*/ic_email.png
- [ ] ./android/res/drawable-*/ic_entrance.png
- [ ] ./android/res/drawable-*/ic_error_36px.png
- [ ] ./android/res/drawable-*/ic_error_red.png
- [ ] ./android/res/drawable-*/ic_error_white.png
- [ ] ./android/res/drawable-*/ic_exit_highway_to_left.png
- [ ] ./android/res/drawable-*/ic_exit_highway_to_right.png
- [ ] ./android/res/drawable-*/ic_expand_less.png
- [ ] ./android/res/drawable-*/ic_expand_more.png
- [ ] ./android/res/drawable-*/ic_explore.png
- [ ] ./android/res/drawable-*/ic_fab_add_night.png
- [ ] ./android/res/drawable-*/ic_fab_add.png
- [ ] ./android/res/drawable-*/ic_fab_view_on_map_night.png
- [ ] ./android/res/drawable-*/ic_fab_view_on_map.png
- [ ] ./android/res/drawable-*/ic_facebook.png
- [ ] ./android/res/drawable-*/ic_fb_disabled.png
- [ ] ./android/res/drawable-*/ic_fb.png
- [ ] ./android/res/drawable-*/ic_filter_list.png
- [ ] ./android/res/drawable-*/ic_follow_and_rotate.png
- [ ] ./android/res/drawable-*/ic_follow.png
- [ ] ./android/res/drawable-*/ic_globe.png
- [ ] ./android/res/drawable-*/ic_google_disabled.png
- [ ] ./android/res/drawable-*/ic_google.png
- [ ] ./android/res/drawable-*/ic_graph_point.png
- [ ] ./android/res/drawable-*/ic_hide.png
- [ ] ./android/res/drawable-*/ic_layers_dark_on.png
- [ ] ./android/res/drawable-*/ic_layers_light_on.png
- [ ] ./android/res/drawable-*/ic_layers_off_night.png
- [ ] ./android/res/drawable-*/ic_layers_off.png
- [ ] ./android/res/drawable-*/ic_layers_on.png
- [ ] ./android/res/drawable-*/ic_leaderboard.png
- [ ] ./android/res/drawable-*/ic_link_inline.png
- [ ] ./android/res/drawable-*/ic_link.png
- [ ] ./android/res/drawable-*/ic_local_expert_default.png
- [ ] ./android/res/drawable-*/ic_lock.png
- [ ] ./android/res/drawable-*/ic_login_fb.png
- [ ] ./android/res/drawable-*/ic_login_google.png
- [ ] ./android/res/drawable-*/ic_logo_uber.png
- [ ] ./android/res/drawable-*/ic_logout.png
- [ ] ./android/res/drawable-*/ic_logo_yandex_taxi.png
- [ ] ./android/res/drawable-*/ic_menu_bookmarks.png
- [ ] ./android/res/drawable-*/ic_menu_close.png
- [ ] ./android/res/drawable-*/ic_menu_discovery.png
- [ ] ./android/res/drawable-*/ic_menu_download_guides.png
- [ ] ./android/res/drawable-*/ic_menu_download.png
- [ ] ./android/res/drawable-*/ic_menu_hotel_search.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_10_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_10.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_11_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_11.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_12_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_12.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_13_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_13.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_14_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_14.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_15_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_15.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_16_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_16.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_17_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_17.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_18_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_18.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_19_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_19.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_1_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_1.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_20_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_20.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_2_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_2.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_3_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_3.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_4_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_4.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_5_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_5.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_6_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_6.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_7_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_7.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_8_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_8.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_9_night.png
- [ ] ./android/res/drawable-*/ic_menu_location_pending_9.png
- [ ] ./android/res/drawable-*/ic_menu_open.png
- [ ] ./android/res/drawable-*/ic_menu_point_to_point.png
- [ ] ./android/res/drawable-*/ic_menu_search.png
- [ ] ./android/res/drawable-*/ic_menu_settings.png
- [ ] ./android/res/drawable-*/ic_menu_share.png
- [ ] ./android/res/drawable-*/ic_mic_white.png
- [ ] ./android/res/drawable-*/ic_minus_red.png
- [ ] ./android/res/drawable-*/ic_more.png
- [ ] ./android/res/drawable-*/ic_my_location.png
- [ ] ./android/res/drawable-*/ic_navigation_light.png
- [ ] ./android/res/drawable-*/ic_not_follow.png
- [ ] ./android/res/drawable-*/ic_opentable.png
- [ ] ./android/res/drawable-*/ic_operating_hours.png
- [ ] ./android/res/drawable-*/ic_operator.png
- [ ] ./android/res/drawable-*/ic_pedestrian.png
- [ ] ./android/res/drawable-*/ic_phone.png
- [ ] ./android/res/drawable-*/ic_place_page_phone.png
- [ ] ./android/res/drawable-*/ic_planning_route_isomaps_dark_on.png
- [ ] ./android/res/drawable-*/ic_plus_green.png
- [ ] ./android/res/drawable-*/ic_plus.png
- [ ] ./android/res/drawable-*/ic_public_inline.png
- [ ] ./android/res/drawable-*/ic_rate_empty.png
- [ ] ./android/res/drawable-*/ic_rate_full.png
- [ ] ./android/res/drawable-*/ic_rate.png
- [ ] ./android/res/drawable-*/ic_route_from.png
- [ ] ./android/res/drawable-*/ic_route_remove.png
- [ ] ./android/res/drawable-*/ic_route_to.png
- [ ] ./android/res/drawable-*/ic_route_via.png
- [ ] ./android/res/drawable-*/ic_routing_atm_off.png
- [ ] ./android/res/drawable-*/ic_routing_atm_on.png
- [ ] ./android/res/drawable-*/ic_routing_eat_off.png
- [ ] ./android/res/drawable-*/ic_routing_eat_on.png
- [ ] ./android/res/drawable-*/ic_routing_error.png
- [ ] ./android/res/drawable-*/ic_routing_food_off.png
- [ ] ./android/res/drawable-*/ic_routing_food_on.png
- [ ] ./android/res/drawable-*/ic_routing_fuel_off.png
- [ ] ./android/res/drawable-*/ic_routing_fuel_on.png
- [ ] ./android/res/drawable-*/ic_routing_parking_off.png
- [ ] ./android/res/drawable-*/ic_routing_parking_on.png
- [ ] ./android/res/drawable-*/ic_routing_search_off.png
- [ ] ./android/res/drawable-*/ic_routing_search_on.png
- [ ] ./android/res/drawable-*/ic_search_my_position.png
- [ ] ./android/res/drawable-*/ic_search.png
- [ ] ./android/res/drawable-*/ic_search_recent.png
- [ ] ./android/res/drawable-*/ic_search_suggest.png
- [ ] ./android/res/drawable-*/ic_setting_traffic_off.png
- [ ] ./android/res/drawable-*/ic_setting_traffic_on.png
- [ ] ./android/res/drawable-*/ic_share_email.png
- [ ] ./android/res/drawable-*/ic_share_message.png
- [ ] ./android/res/drawable-*/ic_share.png
- [ ] ./android/res/drawable-*/ic_show.png
- [ ] ./android/res/drawable-*/ic_sightseeing_checkox.png
- [ ] ./android/res/drawable-*/ic_sort.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_10_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_11_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_12_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_13_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_14_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_15_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_16_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_17_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_18_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_1_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_2_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_3_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_4_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_5_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_6_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_7_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_8_night.png
- [ ] ./android/res/drawable-*/ic_spinner_pending_9_night.png
- [ ] ./android/res/drawable-*/ic_star_small_full.png
- [ ] ./android/res/drawable-*/ic_star_small.png
- [ ] ./android/res/drawable-*/ic_storage_light.png
- [ ] ./android/res/drawable-*/ic_subscribe.png
- [ ] ./android/res/drawable-*/ic_subway_menu_on.png
- [ ] ./android/res/drawable-*/ic_subway_menu.png
- [ ] ./android/res/drawable-*/ic_taxi_logo_maksim.png
- [ ] ./android/res/drawable-*/ic_taxi_logo_vezet.png
- [ ] ./android/res/drawable-*/ic_taxi.png
- [ ] ./android/res/drawable-*/ic_then_exit_highway_to_left.png
- [ ] ./android/res/drawable-*/ic_then_exit_highway_to_right.png
- [ ] ./android/res/drawable-*/ic_then_finish.png
- [ ] ./android/res/drawable-*/ic_then_left.png
- [ ] ./android/res/drawable-*/ic_then_left_sharp.png
- [ ] ./android/res/drawable-*/ic_then_left_slight.png
- [ ] ./android/res/drawable-*/ic_then_right.png
- [ ] ./android/res/drawable-*/ic_then_right_sharp.png
- [ ] ./android/res/drawable-*/ic_then_right_slight.png
- [ ] ./android/res/drawable-*/ic_then_round.png
- [ ] ./android/res/drawable-*/ic_then_uleft.png
- [ ] ./android/res/drawable-*/ic_then_uright.png
- [ ] ./android/res/drawable-*/ic_thumb_up.png
- [ ] ./android/res/drawable-*/ic_traffic_download_1.png
- [ ] ./android/res/drawable-*/ic_traffic_download_2.png
- [ ] ./android/res/drawable-*/ic_traffic_download_3.png
- [ ] ./android/res/drawable-*/ic_traffic_download_night_1.png
- [ ] ./android/res/drawable-*/ic_traffic_download_night_2.png
- [ ] ./android/res/drawable-*/ic_traffic_download_night_3.png
- [ ] ./android/res/drawable-*/ic_traffic_on_night.png
- [ ] ./android/res/drawable-*/ic_traffic_on.png
- [ ] ./android/res/drawable-*/ic_traffic_outdated_night.png
- [ ] ./android/res/drawable-*/ic_traffic_outdated.png
- [ ] ./android/res/drawable-*/ic_transit.png
- [ ] ./android/res/drawable-*/ic_triangle_elevation_night.png
- [ ] ./android/res/drawable-*/ic_triangle_elevation.png
- [ ] ./android/res/drawable-*/ic_triangle_night.png
- [ ] ./android/res/drawable-*/ic_triangle.png
- [ ] ./android/res/drawable-*/ic_turn_direction.png
- [ ] ./android/res/drawable-*/ic_turn_finish.png
- [ ] ./android/res/drawable-*/ic_turn_left.png
- [ ] ./android/res/drawable-*/ic_turn_left_sharp.png
- [ ] ./android/res/drawable-*/ic_turn_left_slight.png
- [ ] ./android/res/drawable-*/ic_turn_right.png
- [ ] ./android/res/drawable-*/ic_turn_right_sharp.png
- [ ] ./android/res/drawable-*/ic_turn_right_slight.png
- [ ] ./android/res/drawable-*/ic_turn_round.png
- [ ] ./android/res/drawable-*/ic_turn_straight.png
- [ ] ./android/res/drawable-*/ic_turn_uleft.png
- [ ] ./android/res/drawable-*/ic_turn_uright.png
- [ ] ./android/res/drawable-*/ic_twitter.png
- [ ] ./android/res/drawable-*/ic_type_text.png
- [ ] ./android/res/drawable-*/ic_undo.png
- [ ] ./android/res/drawable-*/ic_update.png
- [ ] ./android/res/drawable-*/ic_voice_off.png
- [ ] ./android/res/drawable-*/ic_voice_on.png
- [ ] ./android/res/drawable-*/ic_website.png
- [ ] ./android/res/drawable-*/ic_wifi.png
- [ ] ./android/res/drawable-*/ic_wiki.png
- [ ] ./android/res/drawable-*/ic_you_marker.png
- [ ] ./android/res/drawable-*/ic_zoom_in.png
- [ ] ./android/res/drawable-*/ic_zoom_out.png
- [ ] ./android/res/drawable-*/img_annual_subscription_offer.png
- [ ] ./android/res/drawable-*/img_auth.png
- [ ] ./android/res/drawable-*/img_booking_popup_pholder_light.png
- [ ] ./android/res/drawable-*/img_booking_popup_pholder_night.png
- [ ] ./android/res/drawable-*/img_bookmarks.png
- [ ] ./android/res/drawable-*/img_cactus.png
- [ ] ./android/res/drawable-*/img_check_sights_out.png
- [ ] ./android/res/drawable-*/img_discover_guides.png
- [ ] ./android/res/drawable-*/img_dream_and_plan.png
- [ ] ./android/res/drawable-*/img_editonweb.png
- [ ] ./android/res/drawable-*/img_editor_medal.png
- [ ] ./android/res/drawable-*/img_empty_bookmarks.png
- [ ] ./android/res/drawable-*/img_experience.png
- [ ] ./android/res/drawable-*/img_guides_gallery_placeholder.png
- [ ] ./android/res/drawable-*/img_guides_placeholder_land.png
- [ ] ./android/res/drawable-*/img_guides_placeholder.png
- [ ] ./android/res/drawable-*/img_guidespp_placeholder.png
- [ ] ./android/res/drawable-*/img_logo.png
- [ ] ./android/res/drawable-*/img_mappy_heart.png
- [ ] ./android/res/drawable-*/img_migration.png
- [ ] ./android/res/drawable-*/img_monthly_subscription_offer.png
- [ ] ./android/res/drawable-*/img_no_storage_permission.png
- [ ] ./android/res/drawable--*/img_no_storage_permission.png
- [ ] ./android/res/drawable-*/img_onboarding_guide.png
- [ ] ./android/res/drawable-*/img_search_empty_history_light.png
- [ ] ./android/res/drawable-*/img_search_no_maps.png
- [ ] ./android/res/drawable-*/img_search_nothing_found_light.png
- [ ] ./android/res/drawable-*/img_share_emptions.png
- [ ] ./android/res/drawable/img_sharing_editor.png
- [ ] ./android/res/drawable-*/img_sightseeing_footer.png
- [ ] ./android/res/drawable-*/img_sightseeing_subscription.png
- [ ] ./android/res/drawable-*/img_smile.png
- [ ] ./android/res/drawable-*/img_welcome.png
- [ ] ./android/res/drawable-*/logo_luggagehero_dark.png
- [ ] ./android/res/drawable-*/logo_luggagehero_light.png
- [ ] ./android/res/drawable-*/pw_notification.png
- [ ] ./android/res/drawable-*/shadow_bottom.9.png
- [ ] ./android/res/drawable-*/shadow_card.9.png
- [ ] ./android/res/drawable-*/shadow_top.9.png
- [ ] ./android/res/drawable-*/wn_autoupdate.png
- [ ] ./android/res/mipmap-*/ic_launcher.png
- [ ] ./android/res/mipmap-*/ic_launcher_round.png
- [ ] ./android/UnitTests/res/mipmap-*/ic_launcher.png

**Comment by KAMiKAZOW** [comment]
Pretty sure a huge chunk aren't of those copyrightable (too generic, not passing Threshold of Originality). https://github.com/FortAwesome/Font-Awesome has plenty of generic icons, though, under CC BY 4.0 that should be suitable replacements.

**Comment by rtsisyk** [comment]
This one is done.
