### ISSUE TITLE
Icons: inconsistent color palette 

### ISSUE THREAD

**Issue by euf** [organicmaps/organicmaps#7268]
## Context 

To further examine inconsistencies in icons design after #4017 and #7195, I extracted colors from SVGs to count their frequencies. 

1. Rarely used colors may be added by mistake, and these icons should be redrawn to match the palette. 
2. This research helps to visualize current palette, [document it](https://github.com/organicmaps/organicmaps/wiki/Colors#existing-palettes), and make further design choices. 

## Suggested actions

- [ ] Manually examine icons which have rarely used colors and fix them if needed (for example, `chimney-m.svg` seems to have extra colors from Inskscape metadata, and it can disappear after SVG minification)
- [ ] Examine possibility to bring down variations of similar colors: e.g. do we need those different shades of gray? should we settle on a single red for speedcam-alert and railway-crossing?  
- [ ] After reducing palette by removing unnecessary colors write down remaining ones for further icon designs, so that both light and dark styles have simple guidelines describing color choices depending on icon meaning 
- [ ] In the distant future, consider adjusting the palette together with adjusting map colors for better visual impression overall

As usual, comments and discussion is welcome @organicmaps/design!

⚠️ Note that these findings reflect state of things after #7258 by @dvdmrtnz on Jan 28. Tables below should be regenerated when the icons are updated.


## style-clear

|color     | count|sample                                                                                                                                                                                                                                                                                                                                                                                                                                             |icons                                                       |
|:---------|-----:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------|
|`#505050` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/chimney-m.svg"/>                                                                                                                                                                                                                                                                                                                  |chimney-m                                                   |
|`#eeeeee` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/chimney-m.svg"/>                                                                                                                                                                                                                                                                                                                  |chimney-m                                                   |
|`#d1d1d1` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/cross-m.svg"/>                                                                                                                                                                                                                                                                                                                    |cross-m                                                     |
|`#808000` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/cycle_barrier-s.svg"/>                                                                                                                                                                                                                                                                                                            |cycle_barrier-s                                             |
|`#555555` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/dot-m.svg"/>                                                                                                                                                                                                                                                                                                                      |dot-m                                                       |
|`#f51e30` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/speedcam-alert-l.svg"/>                                                                                                                                                                                                                                                                                                           |speedcam-alert-l                                            |
|`#444444` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/transfer_arrow.svg"/>                                                                                                                                                                                                                                                                                                             |transfer_arrow                                              |
|`#727065` |     2|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/chimney-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/power-m.svg"/>                                                                                                                                                                                  |chimney-m, power-m                                          |
|`#c81e17` |     2|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/railway-crossing-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/railway-crossing-m.svg"/>                                                                                                                                                              |railway-crossing-l, railway-crossing-m                      |
|`#000003` |     3|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/star-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/star-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/star-s.svg"/>                                                       |star-l, star-m, star-s                                      |
|`#4e7c90` |     4|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_entrance_private-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_private-s.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_underground_private-m.svg"/> |parking_entrance_private-m, parking_private-m, …            |
|`#000000` |     5|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/cross-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/speedcam-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/volleyball-m.svg"/>                                            |cross-m, skateboard-m, speedcam-m, speedcam-s, volleyball-m |
|`#eeeedd` |     5|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/dot-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/star-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/star-s.svg"/>                                                        |dot-m, ford-m, star-l, star-m, star-s                       |
|`#bb9342` |     8|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bar-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/cafe-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/ice_cream-m.svg"/>                                                   |bar-m, beer-m, cafe-m, fastfood-m, ice_cream-m, …           |
|`#664e42` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/alpine_hut-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/apartment-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/campsite-s.svg"/>                                        |alpine_hut-m, alpine_hut-s, apartment-m, campsite-m, …      |
|`#2e89b0` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bicycle-parking-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking_underground_pay-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/parking-disabled-m.svg"/>             |bicycle-parking-m, motorcycle-parking-m, …                  |
|`#14a0c2` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/drinking-water-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/ford-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/fountain-s.svg"/>                                         |drinking-water-m, drinking-water-s, ford-m, fountain-m, …   |
|`#507f34` |    11|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/garden-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/npark-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/nparkf-outline-m.svg"/>                                          |garden-m, garden-outline-m, npark-m, nparkf-m, …            |
|`#2f6499` |    16|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/airport-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bicycle-rental.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bus-s.svg"/>                                             |airport-m, airport-s, bicycle-rental, bus-m, bus-s, …       |
|`#c15746` |    19|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/alternative-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/audiologist-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/clinic-m.svg"/>                                       |alternative-m, assembly_point-m, audiologist-m, …           |
|`#7f5933` |    63|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/aircraft-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/aquarium-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/archaeological-site-m.svg"/>                                |aircraft-m, anchor-m, aquarium-m, arcade-m, …               |
|`#8c5f93` |    79|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/alcohol-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/art-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/bakery-m.svg"/>                                                   |alcohol-m, antiques-m, art-m, auction-m, bakery-m, …        |
|`#717065` |   135|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/airport_gate-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/archery-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/arrow-s.svg"/>                                           |airport_gate-m, america-football-m, archery-m, arrow-m, …   |
|`#ffffff` |   263|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/airport_gate-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/airport-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-clear/symbols/alpine_hut-m.svg"/>                                      |airport_gate-m, airport-m, airport-s, alcohol-m, …          |


## style-night

|color     | count|sample                                                                                                                                                                                                                                                                                                                                                                                                                                             |icons                                                        |
|:---------|-----:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------|
|`#505050` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/chimney-m.svg"/>                                                                                                                                                                                                                                                                                                                  |chimney-m                                                    |
|`#eeeeee` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/chimney-m.svg"/>                                                                                                                                                                                                                                                                                                                  |chimney-m                                                    |
|`#d1d1d1` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/cross-m.svg"/>                                                                                                                                                                                                                                                                                                                    |cross-m                                                      |
|`#808000` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/cycle_barrier-s.svg"/>                                                                                                                                                                                                                                                                                                            |cycle_barrier-s                                              |
|`#f51e30` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/speedcam-alert-l.svg"/>                                                                                                                                                                                                                                                                                                           |speedcam-alert-l                                             |
|`#444444` |     1|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/transfer_arrow.svg"/>                                                                                                                                                                                                                                                                                                             |transfer_arrow                                               |
|`#c81e17` |     2|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/railway-crossing-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/railway-crossing-m.svg"/>                                                                                                                                                              |railway-crossing-l, railway-crossing-m                       |
|`#000003` |     3|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-s.svg"/>                                                       |star-l, star-m, star-s                                       |
|`#eeeedd` |     3|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-l.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/star-s.svg"/>                                                       |star-l, star-m, star-s                                       |
|`#4e7c90` |     4|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/parking_entrance_private-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/parking_private-s.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/parking_underground_private-m.svg"/> |parking_entrance_private-m, parking_private-m, …             |
|`#bb9342` |     8|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bar-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/cafe-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/ice_cream-m.svg"/>                                                   |bar-m, beer-m, cafe-m, fastfood-m, ice_cream-m, …            |
|`#664e42` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/alpine_hut-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/apartment-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/campsite-s.svg"/>                                        |alpine_hut-m, alpine_hut-s, apartment-m, campsite-m, …       |
|`#2e89b0` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bicycle-parking-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/parking_underground_pay-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/parking-disabled-m.svg"/>             |bicycle-parking-m, motorcycle-parking-m, …                   |
|`#14a0c2` |    10|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/drinking-water-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/ford-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/fountain-s.svg"/>                                         |drinking-water-m, drinking-water-s, ford-m, fountain-m, …    |
|`#507f34` |    11|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/garden-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/npark-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/nparkf-outline-m.svg"/>                                          |garden-m, garden-outline-m, npark-m, nparkf-m, …             |
|`#2f6499` |    16|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/airport-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bicycle-rental.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bus-s.svg"/>                                             |airport-m, airport-s, bicycle-rental, bus-m, bus-s, …        |
|`#ffffff` |    17|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/arrow-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/arrow-xs.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/hotel-s.svg"/>                                                   |arrow-m, arrow-s, arrow-xs, cross-m, hotel-s, npark-m, …     |
|`#c15746` |    19|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/alternative-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/audiologist-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/clinic-m.svg"/>                                       |alternative-m, assembly_point-m, audiologist-m, …            |
|`#111111` |    21|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bicycle-parking-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/motorcycle-parking-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/nparkf-outline-s.svg"/>                    |bicycle-parking-m, garden-outline-m, motorcycle-parking-m, … |
|`#7f5933` |    44|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/aquarium-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/buddhist-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/casino-m.svg"/>                                             |aquarium-m, arcade-m, buddhist-m, buddhist-s, casino-m, …    |
|`#717065` |    67|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/aircraft-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/anchor-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/artwork-m.svg"/>                                              |aircraft-m, airport_gate-m, anchor-m, …                      |
|`#8c5f93` |    79|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/alcohol-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/art-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/bakery-m.svg"/>                                                   |alcohol-m, antiques-m, art-m, auction-m, bakery-m, …         |
|`#777777` |    89|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/america-football-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/australian-football-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/barrier-entrance-s.svg"/>                |america-football-m, archery-m, australian-football-m, …      |
|`#000000` |   223|<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/airport_gate-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/airport-m.svg"/> <img src="https://raw.githubusercontent.com/organicmaps/organicmaps/master/data/styles/clear/style-night/symbols/alpine_hut-m.svg"/>                                      |airport_gate-m, airport-m, airport-s, alcohol-m, …           |


## Extras

These two tables were generated with R script, which
* greps all hex-coded colors from every SVG file
* normalizes them to be lowercase and 6-digits
* excludes all of the subway and light rail icons
* counts the number of files with each color
* pretty-prints the markdown output

<details><summary>Here is the script for reproducibility: </summary >

```r

library(tidyverse)

style <- "clear"
# style <- "night"

setwd(paste0(
  "~/organicmaps/data/styles/clear/style-", style, "/symbols"))

strings <- system('grep -oE "#[0-9A-Fa-f]{3,6}" *.svg | sort', intern = T) %>% 
  gsub(":", ",", .) %>% 
  gsub(".svg", "", .)
strings <- c("icon, color", strings)
csv <- paste(strings, collapse = "\n")

x1 <- read_csv(csv)
x1$color <- tolower(x1$color)
x1$color <- ifelse(nchar(x1$color) == 4,
                   str_replace(x1$color, 
                        "#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])",
                        "#\\1\\1\\2\\2\\3\\3"),
                   x1$color)
                   
x1$transport <- grepl("subway-", x1$icon) | grepl("light.*rail", x1$icon)

pick <- function(x) {
  x <- unique(x)
  if(length(x) <= 3) {
    x
  } else {
    len <- length(x)
    sort(unique(
      c(x[1], 
        x[3],
        x[5],
        x[len])
    ))[1:3]
  }
}

imglinks <- function(style, icon) {
  icon <- pick(icon)
  paste0(
    '<img src="https://raw.githubusercontent.com/organicmaps/organicmaps/',
    'master/data/styles/clear/style-',
    style,
    '/symbols/',
    icon,
    '.svg"/>', collapse = " ")
}


x2 <- x1 %>% 
  filter(!transport) %>% 
  group_by(color) %>% 
  summarise(count = n_distinct(icon), 
            sample = imglinks(style, icon), 
            icons = paste(unique(sort(icon)), collapse = ", ")) %>% 
  arrange(count, icons)


cutstring <- function(strings, n) {
  out <- as.character()
  for (i in seq_along(strings)) {
    string <- strings[i]
    sstring <- str_sub(string, 1, n)
    if(string != sstring) {
      x <- unlist(strsplit(sstring, ", "))
      res <- paste(c(x[1:(length(x)-1)], "…"), collapse = ", ")
    } else {
      res <- string
    }
    out <- c(out, res)
  }
  out
}

x3 <- x2 %>% 
  mutate(color = paste0("`", color, "`"),
         icons = cutstring(icons, 60))
  

x3 %>% knitr::kable() %>% clipr::write_clip()


```  

</details>

**Comment by euf** [comment]
Updated both tables to reflect fixes introduced in #7548 by @dvdmrtnz ❤️
