### ISSUE TITLE
Windows builds TODO

### ISSUE THREAD

**Issue by Osyotr** [organicmaps/organicmaps#7842]
- [ ] Create official `CMakePresets.json`.
- [ ] Fix thirdparty dependency usage:
  - [ ] `Protobuf` (generate `drules_struct.pb.h`/`cpp`).
  - [ ] `fast_double_parser` (always use vendored copy for now, consider removing it (see TODO comment in `qt/main.cpp`)).
  - [ ] `Boost` (Remove hardcoded paths, use imported targets).
  - [ ] `GTest` (some weird usage in drape_tests).
  - [ ] Move `opening_hours` out of `3party/`?
  - [ ] Integrate with vcpkg
- [ ] Fix remaining build issues:
  - [ ] Time-related failures (can probably wait for C++20 for a cleaner fixes):
    - [ ] Replace `std::tm::tm_gmtoff` with something else.
    - [ ] Replace `localtime_r` with something else (`localtime_s`)?
    - [ ] Replace `strptime` with something else.
  - [ ] Fix or remove (C++20?) hack in `TokenizeIteratorBase`.
  - [ ] `#undef FindResource`
- [ ] Fix OpenGL ES usage (use ANGLE?).
  - [ ] Always load functions dynamically
- [ ] Enable QtPositioning on windows
- [ ] Investigate tests failures:
  - [ ] Fix `TmpFile` deleting file before it's closed.

**Comment by biodranik** [comment]
Before going deeply with some fixes, let's discuss them first in separate issues. 

1. Why presets are needed? What pros and cons of config duplication there?
Can we avoid them?

2. We don't use boost libs, only headers. And we should avoid using any libs deps. What are the issues with boost?

3. Fast double parser should be replaced by another, better library, I think it was already mentioned somewhere. 

4. What is the issue with protobuf? There was a pr to migrate to a newer version, although it was stalled due to the increased binary size without any benefits. Maybe it's not an issue anymore with enabled LTO and symbol visibility,need to double check it for Android. 

5. Does updating gtest help? What are the issues there?

Let's start documenting each build and run issue you see on windows in separate issues, and fix them independently, for better efficiency. Some parts of the code can be refactored instead of introducing workarounds.

**Comment by Osyotr** [comment]
> 1. Why presets are needed? What pros and cons of config duplication there?
Can we avoid them?

I find it hard to explain it better than CMake's own [docs](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) do.
With CMake presets it's possible to share exact CMake flags needed to build the project. These settings can be used by IDEs, too.
Note that you are already using some kind of "presets" implicitly - CLion's profiles, VSCode's `CMakeSettings.json`, etc.

> 2. We don't use boost libs, only headers. And we should avoid using any libs deps. What are the issues with boost?

Header-only Boost still requires bootstrapping (including bootstrapping boost.build).
It is also used in a way that does not allow system boost to be used instead. And it's missing `BOOST_ALL_NO_LIB`.

> 3. What is the issue with protobuf?

The vendored copy does not build (`3party\protobuf\protobuf\src\google\protobuf\stubs\hash.h(239): error C2143: syntax error: missing ',' before '<'`). I don't know whether it's because it's outdated or because of wrong vendoring.
It must not depend on `WITH_SYSTEM_PROVIDED_3PARTY` (I'm not sure why it doesn't break for people who set it to `ON`).

> 5. Does updating gtest help? What are the issues there?

The way it's used is... interesting. It's not introduced to the buildsystem until `drape_tests`.
If `WITH_SYSTEM_PROVIDED_3PARTY` is set to `ON`, `find_package(GTest)` is used (correct), but then it links to `gmock` even though GTest does not provide this target (`GTest::gmock` should be used instead).


My opinion:
If you vendor thirdparty dependencies, don't alter their official usage (i.e. don't rename targets, use proper include paths, etc.). And for the love of God, please please please don't use git submodules. Use `FetchContent` instead.
Also consider using package managers on **all** platforms.

**Comment by biodranik** [comment]
1. What settings do you want to preset with CMakeSettings.json? Let's do it on master then, and drop these duplicates you mentioned (CLion, VScode), although I don't fully understand yet what we're talking about.
2. Boost bootstrapping is done now using ./configure.sh, it hints about the script to call on Windows. Any ideas on how to do it better? Using system boost is not a good idea for several reasons, although it can be considered as a parallel alternative to the main approach. Do you propose to define BOOST_ALL_NO_LIB on a global level? It sounds like a good idea. I also don't like many slow submodules in boost, but the only alternative is to keep the generated/bootstrapped set of headers in the repo. We did it in 2010-2016, and it was convenient enough for header-only approach.
3. protobuf dependency on WITH_SYSTEM_PROVIDED_3PARTY should be fixed. There is a PR updating protobuf, but we found that it notably increases the binary size for Android (didn't test for iOS), so that update was postponed. We really use only a small subset of protobuf, so sticking with some older version may be good enough for some time, considering that the build error you mention is fixed. Did you check the log history for that file in the mainstream repo for any MSVC fixes?
4. gmock in drape_tests can be either commented out or moved to another build target (drape_mock_tests for example) which can be safely excluded when necessary. I plan to refactor glyphs part, so those tests may become obsolete anyway.
5. Which package manager would you recommend for iOS or Android? How would guarantee that code that is run on iOS or Android is tested? Running the same code on all desktops is way better than not running the same code but using some random local system package versions instead, and helping contributors (and potential desktop users) fight with the zoo of different issues on different versions. Now even with a brew package manager, we see issues with Qt 6.7 on Macs for example that require manual reverting to Qt 6.6 (brew doesn't do it naturally). If Qt was a submodule, it wasn't an issue.
6. By using submodules instead of copying sources into the repo we make updating easier. And the main benefit is that all builds are reproducible, which is not the case with `FetchContent`. Downloading a lot of deps on configure step may also be unexpected for contributors.

Any fixes and improvements are appreciated!
