### ISSUE TITLE
[ios] Add donation option to Place Page

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#8514]
The original idea and text from @oleg-rswll:

Today two donation link buttons exist, but they are passive and do not let anyone knows about how necessary it is to donate to keep the app running, and without donations the project is at risk of shutting down.  Involving people in supporting the app would help bring them closer together with the community.

**Problem Statement**
There are many people who want to donate to Organic Maps, but today the donation process is too complicated with many steps and no clear request to Donate.

**Criteria**
_Place page_
- Display text and buttons
- Location: on the default view (non-expanded) of the Place - does not require expanding the place page to see
- Text: If trip navigation with Organic Maps was worth a few dollars, donate $4.50 to support this community-developed app, every dollar counts.
- Buttons:
      - €4.50  - redirects to Apple Pay
      - €10
      - €50
      - €85
      - €100
      - Other - redirects to https://donate.organicmaps.app
      - Already Donated - dismisses the section for certain period of time
      - x (to dismiss this section), equivalent to "Already donated"

**Design**

https://www.figma.com/file/0DRA7RWLYNeH1zomKCR7ei/OM-App---Donations?type=design&node-id=0%3A1&mode=design&t=APUtazLydFZ5C14G-1

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/1e849391-1a7b-46a0-a458-03232d4f1090" width="350px">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/0fc850b8-01ea-410f-a417-d66c81ba666b" width="350px">

**TODO/Open questions**

- [ ] More realistic design using native iOS widgets
- [ ] Clarify amounts 
   * For sake of simplicity, amounts will be fixed, in EUR. 
- [ ] Clarify geography
   * Let's try this new section for place page locations in Germany, France, and Benelux (all in EUR).
- [ ] Clarify when to show the section again
   * One year?
- [ ] Figure out how to open Apple Pay via Stripe   
- [ ] Clarify texts

**Comment by biodranik** [comment]
There are several issues with displaying donations on the Place Page. One of the most important issues is "when it should be displayed, to be converted into a donation, instead of being closed and making the user angry?"

Inappropriately displayed prompts look like ads. And annoy users. Especially when a user wants to take a time-sensitive action (decide where to go, start navigation, estimate time or distance, bookmark an important location, edit a nearby POI's opening hours while on the go, etc.)

**Comment by biodranik** [comment]
I do not yet have any idea on when/how the donation in PP should be displayed to avoid annoyance and increase the chance of donation. Any brainstorm from the community is appreciated.

**Comment by oleg-rswll** [comment]
Related to #5952

**Comment by oleg-rswll** [comment]
This is similar to what many services display asking a person to subscribe, for example AllTrails displays about AllTrails+.  This should not be displayed all the time, only specific periods, and should be dismissible.

**Comment by biodranik** [comment]
This is annoying.

**Comment by oleg-rswll** [comment]
Please offer constructive options.

**Comment by biodranik** [comment]
I don't have ready ideas now. Thoughts:
- Users should be already happy with OM to donate (meaning: new users should not see it)
- It should be displayed in a convenient moment, to avoid distracting and being immediately closed/dismissed.
- What is not a convenient moment? Thoughts:
   - Open a POI via API
   - Planning the route to navigate somewhere right now
   - Checking current position and current destination right now
   - Opening OM to add/edit something on the map while nearby
   - Open OM to share something with someone 
   - Some other scenarios? Please add.
- What is a convenient moment? Thoughts:
  - Planning the remote trip while at home (plenty of time, no hurry)
  - Some other scenarios? Please add.

**Comment by kirylkaveryn** [comment]
> Some other scenarios? 

Can we detect someway on the devise, that there was driving trip with navigation and user reach the finish point successfully? Maybe the next launch after this trip?

**Comment by shelvacu** [comment]
I feel very conflicted looking at this issue. If I saw that donation message as it is currently proposed, I would be very frustrated and would be more likely to stop donating than start. On the other hand it seems weird to say organic maps can never ask for a donation.

Perhaps some text could show at the bottom when downloading updated maps? That seems to be the time when I'm using the app but don't have something I'm immediately trying to do.

**Comment by Jean-BaptisteC** [comment]
IMO, it's too intrusive on the place page

**Comment by oleg-rswll** [comment]
Another option is displaying this on the main screen.

**Comment by kirylkaveryn** [comment]
> I feel very conflicted looking at this issue. If I saw that donation message as it is currently proposed, I would be very frustrated and would be more likely to stop donating than start.

Can you explain why?
If you can dismiss this option and don't see it, for example, next 3-6 months? This isn't a persistent option.

**Comment by shelvacu** [comment]
> Can you explain why?

I'm not sure I can 🤔

Mostly it's a case of death by a thousand cuts (where the other 999 aren't organic maps). Far, far too many things replace the thing I'm trying to do with some call to action that I don't want to do. By this point I lose trust when that happens.

**Comment by oleg-rswll** [comment]
Yeah, it's terrible that many commercial apps have very annoying things like ads or promotions. If there is a choice about which apps to use or support, those that are open-source and driven by the community vs those run by VCs and big capital investors, the community ones may be better choices.

**Comment by pastk** [comment]
Also OM should ensure its online before displaying donation UI.

> Perhaps some text could show at the bottom when downloading updated maps? That seems to be the time when I'm using the app but don't have something I'm immediately trying to do.

Yeap!
Could be done both in the downloader screen and the downloading pop-up (which appears after zooming into a not downloaded region).
A text could even mention explicitly that donations are needed to maintain map servers.

Some more ideas where a donation request would seem more natural:

App update notification / download #9247.
"What's New" display (after the app had been updated) - should be dismissable including a "don't show again" option.
A text could mention that donations drive regular releases incl. bug fixes and new features.

Maybe somehow attach donation reminders with newly released bigger features, e.g. track recording, new map styles... I.e. we already try to focus attention on them by adding a red dot. The text is like "Do you like this new feature? Help to bring in more..". But I don't have an idea how to attach it unobtrusively 😊

**Comment by oleg-rswll** [comment]
The map downloads is an unnecessary process right now, it's a chore, and it can be automated. Especially comparing to online maps which do not require managing maps.  So displaying prompt within the "chore" functionality may not yield positive results.

Another place that can be an option is at the end of trip routing.

Another option can be on the main screen, although that should be used sparingly.

**Comment by pastk** [comment]
> The map downloads is an unnecessary process right now, it's a chore, and it can be automated. Especially comparing to online maps which do not require managing maps. So displaying prompt within the "chore" functionality may not yield positive results.
> 

I'd disagree as OM is an offline-first app and users' control over maps download is crucial. Its just unrealistic to fully automate it (means OM should somehow predict which maps to download in advance and which are safe to discard..).

**Comment by oleg-rswll** [comment]
With maps being offline, it's not really possible to automate every aspect of them (unfortunately), so they will still require a person's attention.  But as much as possible should be automated for default settings, while still having fine tuning available for those who want it.

**Comment by pastk** [comment]
There is ongoing work and a continued discussion:
- https://github.com/organicmaps/organicmaps/pull/8638
