### ISSUE TITLE
2024.09 Release Tracking 

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9240]
Expected Store Submission: TBD
Expected Full Rollout to TBD
Release Manager: TBD

- [x] Alpha reminders
 	- [x] PRs for alpha reminder
- [x] Alpha release 
 	- [x] [No release blockers](https://github.com/organicmaps/organicmaps/milestone/9) | Aug 29 | @biodranik
 	- [x] Alpha release notes are ready in Etherpad | Aug 29 | @biodranik
 	- [x] Android smoke-test is OK (15 minutes) | Aug 29 | @biodranik
 	- [x] iOS smoke-test is OK  (15 minutes) | Aug 29 | @biodranik
  	- [x] A new alpha branch is created from the master https://github.com/organicmaps/organicmaps/tree/alpha/2024.08.29
  	- [x] Android Alpha is published on Firebase AppTester for testing  | Aug 29 | @biodranik
 	- [x] Android Alpha is published on Telegram for testing | Aug 29 | @biodranik
 	- [x] iOS Alpha is submitted to Apple TestFlight for review  | Aug 29 | @biodranik
 	- [x] iOS Alpha is approved in Apple TestFlight  | Aug 29 | @biodranik
    - [ ] iOS Alpha TestFlight link is published on Telegram for testing | **missing**
- [x] Release Candidate reminders
 	- [x] Data generation reminder
 	- [ ] The release notes reminder | **overdue** 
 	- [x] ASO reminder | **overdue** 
- [x] Release Candidate | Sun, Sept 8 | TBD
 	- [x] [No release blockers in master](https://github.com/organicmaps/organicmaps/milestone/9)  | TBD
 	- [x] A PR with the actual release notes is raised | Sun, Sept 8 | TBD
 	- [x] Android smoke-test is OK (15 minutes) | Sun, Sept 8 | @rtsisyk
 	- [x] iOS smoke-test is OK (15 minutes) | Sun, Sept 8 | @rtsisyk
 	- [x] A new release branch is created from the master | Sun, Sept 8 | @rtsisyk
 	- [x] A PR with the actual data is raised | Sat, Sept 7 | | @vng 
 	- [ ] RC Sign-off
 	     - [ ] Android is tested by monkey | @rtsisyk
 	     - [x] Android is tested by @rtsisyk
 	     - [ ] Android is tested by @vng
 	     - [ ] <s>iOS is tested by @kirylkaveryn</s>
 	     - [ ] iOS is tested by @vng
 	- [x] The PR with new data is merged into the release branch
 	- [x] The PR with release notes is merged into the release branch
 	- [x] Android RC is submitted to Google Play Closed Beta for review
 	- [x] Android RC is published on GitHub as a pre-release
 	- [x] Android RC APK from Google Play is uploaded to GitHub
 	- [x] Android RC is published on Firebase AppTester for testing
 	- [x] Android RC is published on Telegram for testing
 	- [ ] F-Droid build is triggered | @pastk and TBD to figure out how to check
 	- [x] iOS RC is submitted to Apple TestFlight for review
 	- [ ] Data is synchronized to all servers
 	- [x] Metaserver is updated to include new data version
  	- [x] iOS RC TestFlight is approved | TBD | Tue, Jul 09
 	     - [x] iOS RC TestFlight link is published on Telegram for testing
  	- [x] Android RC is approved for Google Play Closed Beta | TBD
 	     - [x] Google Play Managed Publishing Check
- [ ] Production Release 
 	- [x] iOS RC AppStore metadata is updated | @yanatalia
 	- [x] iOS RC is sent for review to App Store production with automatic 7 days phased rollout
 	- [x] Android RC is sent for review to Google Play Production with automatic 10% phased rollout| TBD
 	- [x] Google Play Managed Publishing Check
 	- [x] Android RC is sent for review to Huawei AppGallery with manual release (TBD) | TBD
  	- [x] Metaserver is updated to include new app versions  | TBD
  	- [ ] Google Play 20% phased rollout | TBD
  	- [x] The release final sign-off
 	     - [ ] Firebase reports by TBD
 	     - [ ] Google Play reports by TBD
 	     - [x] TestFlight reports by TBD
 	     - [x] Email & Telegram reports by TBD
  	- [x] AppStore 100% rollout | TBD
  	- [ ] Google Play 100% rollout | TBD 
  	- [x] App Gallery 100% rollout | TBD
  	- [x] GitHub - remove "pre-release" and mark the release as "latest" | TBD
  	- [x] F-Droid check | TBD
  	- [x] The release branch is merged into master | TBD 
- [ ] News Publishing
  	- [ ] Publish Telegram news post | TBD
  	- [ ] Publish the announcement on Fosstodon | TBD
  	- [ ] Publish the announcement on X (Twitter) | TBD
  	- [ ] Publish news on the website | TBD
  	- [ ] Publish the announcement on Facebook | TBD
  	- [ ] Publish the announcement on Instagram | TBD
  	- [ ] Publish the announcement on Reddit | TBD
  	- [ ] Publish the announcement on LinkedIn | TBD

**Comment by pastk** [comment]
> Since we already had alpha a week ago, I plan to proceed with the regular release procedure as described above in the ticket after getting #9244 fix.

The only concern is that people who use alpha/beta as their daily driver (arguably our most valuable testers) won't have newer 240904 data..

**Comment by pastk** [comment]
> > The only concern is that people who use alpha/beta as their daily driver (arguably our most valuable testers) won't have newer 240904 data..
> 
> What do you suggest? Publish .beta together with the main release?

Yeap, IMO it'd be good (this beta doesn't have to be same as the release, it could include some extra features still to test them)

(we've discussed it already but didn't come to any conclusion https://github.com/organicmaps/organicmaps/issues/8252#issuecomment-2182764974)

**Comment by vng** [comment]
We don't have 240919 release in our Tags https://github.com/organicmaps/organicmaps/tags
