### ISSUE TITLE
2024.10 Release Tracking

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#9439]
**Expected Store Submission:** 2024-10-05
**Expected Full Rollout:** 2024-10-11
**Release Manager:** @rtsisyk

Please post status updates as comments on this ticket while progressing through the checklist. Include links and/or screenshots where applicable.

- [x] The data generator is running.
- [x] The release notes are drafted in Etherpad - was drafted for Beta before.
- [x] No blockers in [2024.10 milestone](https://github.com/organicmaps/organicmaps/milestone/11).
- [x] A PR with the release notes is raised.
- [x] A PR with the new data is raised.
- [ ] QA sign-off:
    - [x] Master has been tested manually on Android by @rtsisyk.
    - [ ] Master has been tested manually on Android by @vng.
    - [x] Master has been tested manually on iOS by @rtsisyk.
    - [ ] Master has been tested manually on iOS by @vng.
    - [x] Master has been tested by [Android Monkey](../.github/workflows/android-monkey.yaml) on the latest master.
- [x] A PR with the new data has been merged into master.
- [x] A new release `release/2024.10.04` branch has been created from master.
- [x] Metaserver is updated to include new data version
- [x] Data synchronization has been started
- [x] [Android Beta](../.github/workflows/android-beta.yaml) pipeline went through on `release/20XX.MM.DD` branch.
- [x] [iOS Beta](../.github/workflows/ios-beta.yaml) pipeline went through on `release/20XX.MM.DD` branch.
- [x] AppStore metadata, screenshots, and keywords are merged into git.
- [x] "App Store Version Release" in the AppStore draft set to "Manually release this version".
- [x] A PR with the release notes has been merged into master.
- [ ] [Android Release](../.github/workflows/android-release.yaml) pipeline went through on `release/20XX.MM.DD` branch.
- [x] [The iOS App draft in AppStore](https://appstoreconnect.apple.com/apps/1567437057/distribution/ios/version/deliverable) has the same date as the release (`20XX.MM.DD`).
- [x] An iOS build from the iOS Beta pipeline has been submitted to review to "Public" testers in [TestFlight](https://appstoreconnect.apple.com/teams/92fab819-8b15-4d04-bd75-2bd32b523c3f/apps/1567437057/testflight).
- [x] "Build" in the AppStore draft set to the build created by the iOS Beta pipeline.
- [x] [iOS Release](../.github/workflows/ios-release.yaml) pipeline went through on `release/20XX.MM.DD` branch - **only metadata, without screenshots**.
- [x] "Phased Release for App Store Automatic Updates" in the AppStore draft set to "Release update over 7-day period using phased release".
- [x] AppStore (PROD) has been sent to review.
- [x] Android signed APK from Google Play has been uploaded to the GitHub Release as `OrganicMaps-YYMMDDNN-google-release.apk`.
- [x] Android Web (`OrganicMaps-YYMMDDNN-web-release.apk`) and Google Play (`OrganicMaps-YYMMDDNN-google-release.apk`) APKs are shared in Telegram with the release notes.
- [x] Google Play Production sent for a review with automatic <s>10%</s>1% phased rollout
- [x] Data is synchronized
- [ ] iOS RC TestFlight is approved
- [ ] iOS RC TestFlight link is published on Telegram with the release notes.
- [x] F-Droid [knows about the new build](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/app.organicmaps.yml).
- [ ] Google Play Closed Beta is approved and published via Managed Publishing to 100%.
- [ ] Google Play Managed Publishing Check
- [x] Android RC is sent for review to Huawei AppGallery with manual release (TBD)
- [ ] Metaserver is updated to include new app versions 
- [ ] Google Play 20% phased rollout
- [ ] The release final sign-off
	- [ ] Firebase reports by TBD
	- [ ] Google Play reports by TBD
	- [ ] TestFlight reports by TBD
	- [ ] Email & Telegram reports by TBD
- [x] AppStore 100% rollout
- [x] Google Play 100% rollout
- [x] App Gallery 100% rollout
- [x] GitHub - remove "pre-release" and mark the release as "latest"
- [x] F-Droid build status check
- [ ] The release branch is merged into master
- [ ] News Publishing
  	- [ ] Publish Telegram news post
  	- [ ] Publish the announcement on Fosstodon
  	- [ ] Publish the announcement on X (Twitter)
  	- [ ] Publish news on the website
  	- [ ] Publish the announcement on Facebook
  	- [ ] Publish the announcement on Instagram
  	- [ ] Publish the announcement on Reddit
  	- [ ] Publish the announcement on LinkedIn

**Comment by Jean-BaptisteC** [comment]
New screenshots continue to be not available on Play Store, maybe upload new screenshots manually

**Comment by pastk** [comment]
This regression might need hotfix:
- https://github.com/organicmaps/organicmaps/issues/9522

**Comment by bfontaine** [comment]
This can be closed, right?
