### ISSUE TITLE
Bicycle routing improvements overview

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#9748]
- [ ] reduce preference for bicycle=yes and #9593
- [ ] add a small penalty to passable cycle barriers (and gates?)
- [ ] differentiate between various types of on-road lanes (shared, dedicated, separated..)
- [ ] consider more road's attributes: maxspeed (low speed is better), number of lanes (low is better), shoulder (no shoulder is bad), lit
- [ ] https://github.com/organicmaps/organicmaps/issues/9709
- [ ] give a minor but uniform bonus to bicycle routes #9698 
- [ ] penalties for road crossings and https://github.com/organicmaps/organicmaps/issues/1845
- [ ] avoid small detours from straight roads (e.g. from primary into gas station by service and 100m later back to primary); maybe turn penalties will solve it already?
- [ ] prefer known good quality tracks & paths over regular (with no additional tags, now they're considered `unpaved_good`)
- [ ] more grades for road quality and more cycling specific (e.g. cobblestone could be ok for cars, but is terrible for bicycles)

**Comment by matkoniecz** [comment]
Do we need more tests for any such case? I would be happy to provide some, may also canvass for more people so not all examples will be from Kraków.

> number of lanes (low is better)

this is a great indicator: >1 lane in one direction is quite terrible, even with dedicated lane or separate cycleway. Cycleway along busy road is worse than parallel residential away from noise. 

Though note that turn lanes have a far more limited impact. May solve itself given their limited length.

> shoulder (no shoulder is bad), lit

"no shoulder is bad" - I would rather say that lack of shoulder makes multi-lane high-speed even worse, missing shoulder on calm ways is 100% fine

> consider more road's attributes: maxspeed (low speed is better)

Some places (notably Ireland) like to have absurdly high speed limits in some places making it a bit tricky to rely on this. See

![screen01](https://github.com/user-attachments/assets/61c49076-8d22-4990-9b10-717d7d2b7002)

Also, many calm ones have simply default speed limits

**Comment by matkoniecz** [comment]
>  add a small penalty to passable cycle barriers (and gates?)

maybe also large penalty to elevators, medium one to level crossings (with train) and small penalty to crossing tram tracks?

**Comment by pastk** [comment]
> Do we need more tests for any such case? I would be happy to provide some (initially few, once #9692 is merged I can spend multiple hours on finding good test cases), may also canvass for more people so not all examples will be from Kraków.
> 

Yeap more tests are helpful! 1-2 per case would be enough for a start, its better to add them into case-specific tickets, rather than pile in one issue. Of course its also good to have cases from different people and regions.
And naturally people will report new and misc cases over time..
Actually I'm not sure when I'm going to put more work into bicycle routing improvements, so no need to rush, but of course good to have discussions going, etc.

Also it'd be great to create more specific tickets e.g. "Consider more road's attributes for bicycle routing" and put your comments re maxspeed, shoulder etc there and have more people to chime in with their opinion.. :pray:

**Comment by pastk** [comment]
Added "penalize road tunnels".

**Comment by pastk** [comment]
Added "too much weight on elevation difference".

**Comment by patepelo** [comment]
> Added "penalize road tunnels".

> A user has provided feedback about a cycling route in Norway:
> Organic Maps routes cyclists through a narrow, approximately 7 km long tunnel that's considered hazardous, although legally allowed for cyclists.

++1 to "less weight for tunnels without light and no shoulders." and other examples
